services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: study_pal_backend
    ports:
      - "8080:8080"
    volumes:
      - ./:/src
    environment:
      - TZ=Asia/Tokyo
    command: air
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: study_pal_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: study_pal
    volumes:
      - db-store:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  db-store: