// Code generated by ent, DO NOT EDIT.

package workbookcategorydetail

import (
	"study-pal-backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldEQ(FieldName, v))
}

// WorkbookCategoryID applies equality check predicate on the "workbook_category_id" field. It's identical to WorkbookCategoryIDEQ.
func WorkbookCategoryID(v uuid.UUID) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldEQ(FieldWorkbookCategoryID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldContainsFold(FieldName, v))
}

// WorkbookCategoryIDEQ applies the EQ predicate on the "workbook_category_id" field.
func WorkbookCategoryIDEQ(v uuid.UUID) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldEQ(FieldWorkbookCategoryID, v))
}

// WorkbookCategoryIDNEQ applies the NEQ predicate on the "workbook_category_id" field.
func WorkbookCategoryIDNEQ(v uuid.UUID) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldNEQ(FieldWorkbookCategoryID, v))
}

// WorkbookCategoryIDIn applies the In predicate on the "workbook_category_id" field.
func WorkbookCategoryIDIn(vs ...uuid.UUID) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldIn(FieldWorkbookCategoryID, vs...))
}

// WorkbookCategoryIDNotIn applies the NotIn predicate on the "workbook_category_id" field.
func WorkbookCategoryIDNotIn(vs ...uuid.UUID) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldNotIn(FieldWorkbookCategoryID, vs...))
}

// WorkbookCategoryIDGT applies the GT predicate on the "workbook_category_id" field.
func WorkbookCategoryIDGT(v uuid.UUID) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldGT(FieldWorkbookCategoryID, v))
}

// WorkbookCategoryIDGTE applies the GTE predicate on the "workbook_category_id" field.
func WorkbookCategoryIDGTE(v uuid.UUID) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldGTE(FieldWorkbookCategoryID, v))
}

// WorkbookCategoryIDLT applies the LT predicate on the "workbook_category_id" field.
func WorkbookCategoryIDLT(v uuid.UUID) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldLT(FieldWorkbookCategoryID, v))
}

// WorkbookCategoryIDLTE applies the LTE predicate on the "workbook_category_id" field.
func WorkbookCategoryIDLTE(v uuid.UUID) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.FieldLTE(FieldWorkbookCategoryID, v))
}

// HasDescriptionProblems applies the HasEdge predicate on the "description_problems" edge.
func HasDescriptionProblems() predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DescriptionProblemsTable, DescriptionProblemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDescriptionProblemsWith applies the HasEdge predicate on the "description_problems" edge with a given conditions (other predicates).
func HasDescriptionProblemsWith(preds ...predicate.DescriptionProblem) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(func(s *sql.Selector) {
		step := newDescriptionProblemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSelectionProblems applies the HasEdge predicate on the "selection_problems" edge.
func HasSelectionProblems() predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SelectionProblemsTable, SelectionProblemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSelectionProblemsWith applies the HasEdge predicate on the "selection_problems" edge with a given conditions (other predicates).
func HasSelectionProblemsWith(preds ...predicate.SelectionProblem) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(func(s *sql.Selector) {
		step := newSelectionProblemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTrueOrFalseProblems applies the HasEdge predicate on the "true_or_false_problems" edge.
func HasTrueOrFalseProblems() predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TrueOrFalseProblemsTable, TrueOrFalseProblemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTrueOrFalseProblemsWith applies the HasEdge predicate on the "true_or_false_problems" edge with a given conditions (other predicates).
func HasTrueOrFalseProblemsWith(preds ...predicate.TrueOrFalseProblem) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(func(s *sql.Selector) {
		step := newTrueOrFalseProblemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkbookCategoryDetail) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkbookCategoryDetail) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkbookCategoryDetail) predicate.WorkbookCategoryDetail {
	return predicate.WorkbookCategoryDetail(sql.NotPredicates(p))
}
