@startuml erd

entity "articles" as Article {
    + id: uuid
    --
    * page_id: int
    * description: varchar(400)
    * user_id: uuid
    * created_at: datetime
    * updated_at: datetime
}

entity "description_problems" as DescriptionProblem {
    + id: uuid
    --
    * correct_statement varchar(255)
    * statement: varchar(1000)
    * workbook_id: uuid
    * workbook_category_id: uuid
    * workbook_category_detail_id: uuid
    * created_at: datetime
    * updated_at: datetime
}

entity "permissions" as Permission {
    + id: uuid
    --
    * name: varchar(255)
    * created_at: datetime
    * updated_at: datetime
}

entity "permission_roles" as PermissionRole {
    + id: uuid
    --
    * permission_id: uuid
    * role_id: uuid
}

entity "roles" as Role {
    + id: uuid
    --
    * statement: varchar(255)
    * created_at: datetime
    * updated_at: datetime
}

entity "selection_problems" as SelectionProblem {
    + id: uuid
    --
    * statement: varchar(1000)
    * workbook_id: uuid
    * workbook_category_id: uuid
    * workbook_category_detail_id: uuid
    * created_at: datetime
    * updated_at: datetime
}

entity "selection_problem_answers" as SelectionProblemAnswer {
    + id: uuid
    --
    * is_correct: boolean
    * selection_problem_id: uuid
    * statement: varchar(255)
    * created_at: datetime
    * updated_at: datetime
}

entity "true_or_false_problem" as TrueOrFalseProblem {
    + id: uuid
    --
    * is_correct: boolean
    * statement: varchar(255)
    * workbook_id: uuid
    * workbook_category_id: uuid
    * workbook_category_detail_id: uuid
    * created_at: datetime
    * updated_at: datetime
}

entity "users" as User {
    + id: uuid
    --
    * email: varchar(255)
    * name: varchar(255)
    * nick_name: varchar(255)
    * password: text
    * created_at: datetime
    * updated_at: datetime
}

entity "workbooks" as Workbook {
    + id: uuid
    --
    * description: varchar(400)
    * is_public: boolean
    * title: varchar(255)
    * user_id: uuid
    * created_at: datetime
    * updated_at: datetime
}

entity "workbook_categories" as WorkbookCategory {
    + id: uuid
    --
    * name: varchar(400)
    * workbook_id: uuid
    * created_at: datetime
    * updated_at: datetime
}

entity "workbook_category_details" as WorkbookCategoryDetail {
    + id: uuid
    --
    * name: varchar(400)
    * workbook_category_id: uuid
    * created_at: datetime
    * updated_at: datetime
}

entity "workbook_members" as WorkbookMember {
    + id: uuid
    --
    * role_id: uuid
    * user_id: uuid
    * workbook_id: uuid
    * created_at: datetime
    * updated_at: datetime
}


Article }|--|| User
DescriptionProblem }o--|| Workbook
DescriptionProblem }o--|| WorkbookCategory
DescriptionProblem }o--|| WorkbookCategoryDetail
Permission ||--|{ PermissionRole
Role ||--|{ PermissionRole
Role ||--|{ WorkbookMember
SelectionProblem }o--|| Workbook
SelectionProblem }o--|| WorkbookCategory
SelectionProblem }o--|| WorkbookCategoryDetail
SelectionProblemAnswer }|--|| SelectionProblem
TrueOrFalseProblem }o--|| Workbook
TrueOrFalseProblem }o--|| WorkbookCategory
TrueOrFalseProblem }o--|| WorkbookCategoryDetail
Workbook ||--|{ WorkbookMember
Workbook ||--o{ WorkbookCategory
WorkbookCategory ||--o{ WorkbookCategoryDetail
WorkbookMember }|--|| User

@enduml