// Code generated by ent, DO NOT EDIT.

package answermultichoices

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the answermultichoices type in the database.
	Label = "answer_multi_choices"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldIsCorrect holds the string denoting the is_correct field in the database.
	FieldIsCorrect = "is_correct"
	// Table holds the table name of the answermultichoices in the database.
	Table = "answer_multi_choices"
)

// Columns holds all SQL columns for answermultichoices fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldIsCorrect,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "answer_multi_choices"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"problem_answer_multi_choices",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
)

// OrderOption defines the ordering options for the AnswerMultiChoices queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByIsCorrect orders the results by the is_correct field.
func ByIsCorrect(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsCorrect, opts...).ToFunc()
}
