// Code generated by ent, DO NOT EDIT.

package answermultichoices

import (
	"study-pal-backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldEQ(FieldName, v))
}

// ProblemID applies equality check predicate on the "problem_id" field. It's identical to ProblemIDEQ.
func ProblemID(v int) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldEQ(FieldProblemID, v))
}

// IsCorrect applies equality check predicate on the "is_correct" field. It's identical to IsCorrectEQ.
func IsCorrect(v bool) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldEQ(FieldIsCorrect, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldContainsFold(FieldName, v))
}

// ProblemIDEQ applies the EQ predicate on the "problem_id" field.
func ProblemIDEQ(v int) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldEQ(FieldProblemID, v))
}

// ProblemIDNEQ applies the NEQ predicate on the "problem_id" field.
func ProblemIDNEQ(v int) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldNEQ(FieldProblemID, v))
}

// ProblemIDIn applies the In predicate on the "problem_id" field.
func ProblemIDIn(vs ...int) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldIn(FieldProblemID, vs...))
}

// ProblemIDNotIn applies the NotIn predicate on the "problem_id" field.
func ProblemIDNotIn(vs ...int) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldNotIn(FieldProblemID, vs...))
}

// IsCorrectEQ applies the EQ predicate on the "is_correct" field.
func IsCorrectEQ(v bool) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldEQ(FieldIsCorrect, v))
}

// IsCorrectNEQ applies the NEQ predicate on the "is_correct" field.
func IsCorrectNEQ(v bool) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.FieldNEQ(FieldIsCorrect, v))
}

// HasProblem applies the HasEdge predicate on the "problem" edge.
func HasProblem() predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProblemTable, ProblemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProblemWith applies the HasEdge predicate on the "problem" edge with a given conditions (other predicates).
func HasProblemWith(preds ...predicate.Problem) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(func(s *sql.Selector) {
		step := newProblemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AnswerMultiChoices) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AnswerMultiChoices) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AnswerMultiChoices) predicate.AnswerMultiChoices {
	return predicate.AnswerMultiChoices(sql.NotPredicates(p))
}
