// Code generated by ent, DO NOT EDIT.

package workbookinvitationmember

import (
	"study-pal-backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldEQ(FieldUpdatedAt, v))
}

// EffectiveAt applies equality check predicate on the "effective_at" field. It's identical to EffectiveAtEQ.
func EffectiveAt(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldEQ(FieldEffectiveAt, v))
}

// IsInvited applies equality check predicate on the "is_invited" field. It's identical to IsInvitedEQ.
func IsInvited(v bool) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldEQ(FieldIsInvited, v))
}

// RoleID applies equality check predicate on the "role_id" field. It's identical to RoleIDEQ.
func RoleID(v uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldEQ(FieldRoleID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldEQ(FieldUserID, v))
}

// WorkbookID applies equality check predicate on the "workbook_id" field. It's identical to WorkbookIDEQ.
func WorkbookID(v uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldEQ(FieldWorkbookID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldLTE(FieldUpdatedAt, v))
}

// EffectiveAtEQ applies the EQ predicate on the "effective_at" field.
func EffectiveAtEQ(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldEQ(FieldEffectiveAt, v))
}

// EffectiveAtNEQ applies the NEQ predicate on the "effective_at" field.
func EffectiveAtNEQ(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldNEQ(FieldEffectiveAt, v))
}

// EffectiveAtIn applies the In predicate on the "effective_at" field.
func EffectiveAtIn(vs ...time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldIn(FieldEffectiveAt, vs...))
}

// EffectiveAtNotIn applies the NotIn predicate on the "effective_at" field.
func EffectiveAtNotIn(vs ...time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldNotIn(FieldEffectiveAt, vs...))
}

// EffectiveAtGT applies the GT predicate on the "effective_at" field.
func EffectiveAtGT(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldGT(FieldEffectiveAt, v))
}

// EffectiveAtGTE applies the GTE predicate on the "effective_at" field.
func EffectiveAtGTE(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldGTE(FieldEffectiveAt, v))
}

// EffectiveAtLT applies the LT predicate on the "effective_at" field.
func EffectiveAtLT(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldLT(FieldEffectiveAt, v))
}

// EffectiveAtLTE applies the LTE predicate on the "effective_at" field.
func EffectiveAtLTE(v time.Time) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldLTE(FieldEffectiveAt, v))
}

// IsInvitedEQ applies the EQ predicate on the "is_invited" field.
func IsInvitedEQ(v bool) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldEQ(FieldIsInvited, v))
}

// IsInvitedNEQ applies the NEQ predicate on the "is_invited" field.
func IsInvitedNEQ(v bool) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldNEQ(FieldIsInvited, v))
}

// RoleIDEQ applies the EQ predicate on the "role_id" field.
func RoleIDEQ(v uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldEQ(FieldRoleID, v))
}

// RoleIDNEQ applies the NEQ predicate on the "role_id" field.
func RoleIDNEQ(v uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldNEQ(FieldRoleID, v))
}

// RoleIDIn applies the In predicate on the "role_id" field.
func RoleIDIn(vs ...uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldIn(FieldRoleID, vs...))
}

// RoleIDNotIn applies the NotIn predicate on the "role_id" field.
func RoleIDNotIn(vs ...uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldNotIn(FieldRoleID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldNotIn(FieldUserID, vs...))
}

// WorkbookIDEQ applies the EQ predicate on the "workbook_id" field.
func WorkbookIDEQ(v uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldEQ(FieldWorkbookID, v))
}

// WorkbookIDNEQ applies the NEQ predicate on the "workbook_id" field.
func WorkbookIDNEQ(v uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldNEQ(FieldWorkbookID, v))
}

// WorkbookIDIn applies the In predicate on the "workbook_id" field.
func WorkbookIDIn(vs ...uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldIn(FieldWorkbookID, vs...))
}

// WorkbookIDNotIn applies the NotIn predicate on the "workbook_id" field.
func WorkbookIDNotIn(vs ...uuid.UUID) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.FieldNotIn(FieldWorkbookID, vs...))
}

// HasRole applies the HasEdge predicate on the "role" edge.
func HasRole() predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoleTable, RoleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoleWith applies the HasEdge predicate on the "role" edge with a given conditions (other predicates).
func HasRoleWith(preds ...predicate.Role) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(func(s *sql.Selector) {
		step := newRoleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWorkbook applies the HasEdge predicate on the "workbook" edge.
func HasWorkbook() predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WorkbookTable, WorkbookColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkbookWith applies the HasEdge predicate on the "workbook" edge with a given conditions (other predicates).
func HasWorkbookWith(preds ...predicate.Workbook) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(func(s *sql.Selector) {
		step := newWorkbookStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WorkbookInvitationMember) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WorkbookInvitationMember) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WorkbookInvitationMember) predicate.WorkbookInvitationMember {
	return predicate.WorkbookInvitationMember(sql.NotPredicates(p))
}
