// Code generated by ent, DO NOT EDIT.

package descriptionproblem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the descriptionproblem type in the database.
	Label = "description_problem"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCorrectStatement holds the string denoting the correct_statement field in the database.
	FieldCorrectStatement = "correct_statement"
	// FieldStatement holds the string denoting the statement field in the database.
	FieldStatement = "statement"
	// FieldWorkbookID holds the string denoting the workbook_id field in the database.
	FieldWorkbookID = "workbook_id"
	// FieldWorkbookCategoryID holds the string denoting the workbook_category_id field in the database.
	FieldWorkbookCategoryID = "workbook_category_id"
	// EdgeWorkbook holds the string denoting the workbook edge name in mutations.
	EdgeWorkbook = "workbook"
	// EdgeWorkbookCategory holds the string denoting the workbook_category edge name in mutations.
	EdgeWorkbookCategory = "workbook_category"
	// Table holds the table name of the descriptionproblem in the database.
	Table = "description_problems"
	// WorkbookTable is the table that holds the workbook relation/edge.
	WorkbookTable = "description_problems"
	// WorkbookInverseTable is the table name for the Workbook entity.
	// It exists in this package in order to avoid circular dependency with the "workbook" package.
	WorkbookInverseTable = "workbooks"
	// WorkbookColumn is the table column denoting the workbook relation/edge.
	WorkbookColumn = "workbook_id"
	// WorkbookCategoryTable is the table that holds the workbook_category relation/edge.
	WorkbookCategoryTable = "description_problems"
	// WorkbookCategoryInverseTable is the table name for the WorkbookCategory entity.
	// It exists in this package in order to avoid circular dependency with the "workbookcategory" package.
	WorkbookCategoryInverseTable = "workbook_categories"
	// WorkbookCategoryColumn is the table column denoting the workbook_category relation/edge.
	WorkbookCategoryColumn = "workbook_category_id"
)

// Columns holds all SQL columns for descriptionproblem fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCorrectStatement,
	FieldStatement,
	FieldWorkbookID,
	FieldWorkbookCategoryID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// CorrectStatementValidator is a validator for the "correct_statement" field. It is called by the builders before save.
	CorrectStatementValidator func(string) error
	// StatementValidator is a validator for the "statement" field. It is called by the builders before save.
	StatementValidator func(string) error
)

// OrderOption defines the ordering options for the DescriptionProblem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCorrectStatement orders the results by the correct_statement field.
func ByCorrectStatement(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCorrectStatement, opts...).ToFunc()
}

// ByStatement orders the results by the statement field.
func ByStatement(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatement, opts...).ToFunc()
}

// ByWorkbookID orders the results by the workbook_id field.
func ByWorkbookID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkbookID, opts...).ToFunc()
}

// ByWorkbookCategoryID orders the results by the workbook_category_id field.
func ByWorkbookCategoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkbookCategoryID, opts...).ToFunc()
}

// ByWorkbookField orders the results by workbook field.
func ByWorkbookField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWorkbookStep(), sql.OrderByField(field, opts...))
	}
}

// ByWorkbookCategoryField orders the results by workbook_category field.
func ByWorkbookCategoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWorkbookCategoryStep(), sql.OrderByField(field, opts...))
	}
}
func newWorkbookStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WorkbookInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, WorkbookTable, WorkbookColumn),
	)
}
func newWorkbookCategoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WorkbookCategoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, WorkbookCategoryTable, WorkbookCategoryColumn),
	)
}
