// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"study-pal-backend/ent/answertype"
	"study-pal-backend/ent/problem"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AnswerTypeCreate is the builder for creating a AnswerType entity.
type AnswerTypeCreate struct {
	config
	mutation *AnswerTypeMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (atc *AnswerTypeCreate) SetCreatedAt(t time.Time) *AnswerTypeCreate {
	atc.mutation.SetCreatedAt(t)
	return atc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (atc *AnswerTypeCreate) SetNillableCreatedAt(t *time.Time) *AnswerTypeCreate {
	if t != nil {
		atc.SetCreatedAt(*t)
	}
	return atc
}

// SetUpdatedAt sets the "updated_at" field.
func (atc *AnswerTypeCreate) SetUpdatedAt(t time.Time) *AnswerTypeCreate {
	atc.mutation.SetUpdatedAt(t)
	return atc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (atc *AnswerTypeCreate) SetNillableUpdatedAt(t *time.Time) *AnswerTypeCreate {
	if t != nil {
		atc.SetUpdatedAt(*t)
	}
	return atc
}

// SetName sets the "name" field.
func (atc *AnswerTypeCreate) SetName(s string) *AnswerTypeCreate {
	atc.mutation.SetName(s)
	return atc
}

// SetID sets the "id" field.
func (atc *AnswerTypeCreate) SetID(u uuid.UUID) *AnswerTypeCreate {
	atc.mutation.SetID(u)
	return atc
}

// AddProblemIDs adds the "problems" edge to the Problem entity by IDs.
func (atc *AnswerTypeCreate) AddProblemIDs(ids ...uuid.UUID) *AnswerTypeCreate {
	atc.mutation.AddProblemIDs(ids...)
	return atc
}

// AddProblems adds the "problems" edges to the Problem entity.
func (atc *AnswerTypeCreate) AddProblems(p ...*Problem) *AnswerTypeCreate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return atc.AddProblemIDs(ids...)
}

// Mutation returns the AnswerTypeMutation object of the builder.
func (atc *AnswerTypeCreate) Mutation() *AnswerTypeMutation {
	return atc.mutation
}

// Save creates the AnswerType in the database.
func (atc *AnswerTypeCreate) Save(ctx context.Context) (*AnswerType, error) {
	atc.defaults()
	return withHooks(ctx, atc.sqlSave, atc.mutation, atc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (atc *AnswerTypeCreate) SaveX(ctx context.Context) *AnswerType {
	v, err := atc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (atc *AnswerTypeCreate) Exec(ctx context.Context) error {
	_, err := atc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atc *AnswerTypeCreate) ExecX(ctx context.Context) {
	if err := atc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (atc *AnswerTypeCreate) defaults() {
	if _, ok := atc.mutation.CreatedAt(); !ok {
		v := answertype.DefaultCreatedAt()
		atc.mutation.SetCreatedAt(v)
	}
	if _, ok := atc.mutation.UpdatedAt(); !ok {
		v := answertype.DefaultUpdatedAt()
		atc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (atc *AnswerTypeCreate) check() error {
	if _, ok := atc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AnswerType.created_at"`)}
	}
	if _, ok := atc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AnswerType.updated_at"`)}
	}
	if _, ok := atc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AnswerType.name"`)}
	}
	if v, ok := atc.mutation.Name(); ok {
		if err := answertype.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AnswerType.name": %w`, err)}
		}
	}
	return nil
}

func (atc *AnswerTypeCreate) sqlSave(ctx context.Context) (*AnswerType, error) {
	if err := atc.check(); err != nil {
		return nil, err
	}
	_node, _spec := atc.createSpec()
	if err := sqlgraph.CreateNode(ctx, atc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	atc.mutation.id = &_node.ID
	atc.mutation.done = true
	return _node, nil
}

func (atc *AnswerTypeCreate) createSpec() (*AnswerType, *sqlgraph.CreateSpec) {
	var (
		_node = &AnswerType{config: atc.config}
		_spec = sqlgraph.NewCreateSpec(answertype.Table, sqlgraph.NewFieldSpec(answertype.FieldID, field.TypeUUID))
	)
	if id, ok := atc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := atc.mutation.CreatedAt(); ok {
		_spec.SetField(answertype.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := atc.mutation.UpdatedAt(); ok {
		_spec.SetField(answertype.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := atc.mutation.Name(); ok {
		_spec.SetField(answertype.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if nodes := atc.mutation.ProblemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   answertype.ProblemsTable,
			Columns: []string{answertype.ProblemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AnswerTypeCreateBulk is the builder for creating many AnswerType entities in bulk.
type AnswerTypeCreateBulk struct {
	config
	err      error
	builders []*AnswerTypeCreate
}

// Save creates the AnswerType entities in the database.
func (atcb *AnswerTypeCreateBulk) Save(ctx context.Context) ([]*AnswerType, error) {
	if atcb.err != nil {
		return nil, atcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(atcb.builders))
	nodes := make([]*AnswerType, len(atcb.builders))
	mutators := make([]Mutator, len(atcb.builders))
	for i := range atcb.builders {
		func(i int, root context.Context) {
			builder := atcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnswerTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, atcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, atcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, atcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (atcb *AnswerTypeCreateBulk) SaveX(ctx context.Context) []*AnswerType {
	v, err := atcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (atcb *AnswerTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := atcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atcb *AnswerTypeCreateBulk) ExecX(ctx context.Context) {
	if err := atcb.Exec(ctx); err != nil {
		panic(err)
	}
}
