// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"study-pal-backend/ent/answermultichoices"
	"study-pal-backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AnswerMultiChoicesUpdate is the builder for updating AnswerMultiChoices entities.
type AnswerMultiChoicesUpdate struct {
	config
	hooks    []Hook
	mutation *AnswerMultiChoicesMutation
}

// Where appends a list predicates to the AnswerMultiChoicesUpdate builder.
func (amcu *AnswerMultiChoicesUpdate) Where(ps ...predicate.AnswerMultiChoices) *AnswerMultiChoicesUpdate {
	amcu.mutation.Where(ps...)
	return amcu
}

// SetName sets the "name" field.
func (amcu *AnswerMultiChoicesUpdate) SetName(s string) *AnswerMultiChoicesUpdate {
	amcu.mutation.SetName(s)
	return amcu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (amcu *AnswerMultiChoicesUpdate) SetNillableName(s *string) *AnswerMultiChoicesUpdate {
	if s != nil {
		amcu.SetName(*s)
	}
	return amcu
}

// SetIsCorrect sets the "is_correct" field.
func (amcu *AnswerMultiChoicesUpdate) SetIsCorrect(b bool) *AnswerMultiChoicesUpdate {
	amcu.mutation.SetIsCorrect(b)
	return amcu
}

// SetNillableIsCorrect sets the "is_correct" field if the given value is not nil.
func (amcu *AnswerMultiChoicesUpdate) SetNillableIsCorrect(b *bool) *AnswerMultiChoicesUpdate {
	if b != nil {
		amcu.SetIsCorrect(*b)
	}
	return amcu
}

// Mutation returns the AnswerMultiChoicesMutation object of the builder.
func (amcu *AnswerMultiChoicesUpdate) Mutation() *AnswerMultiChoicesMutation {
	return amcu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (amcu *AnswerMultiChoicesUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, amcu.sqlSave, amcu.mutation, amcu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (amcu *AnswerMultiChoicesUpdate) SaveX(ctx context.Context) int {
	affected, err := amcu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (amcu *AnswerMultiChoicesUpdate) Exec(ctx context.Context) error {
	_, err := amcu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (amcu *AnswerMultiChoicesUpdate) ExecX(ctx context.Context) {
	if err := amcu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (amcu *AnswerMultiChoicesUpdate) check() error {
	if v, ok := amcu.mutation.Name(); ok {
		if err := answermultichoices.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AnswerMultiChoices.name": %w`, err)}
		}
	}
	return nil
}

func (amcu *AnswerMultiChoicesUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := amcu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(answermultichoices.Table, answermultichoices.Columns, sqlgraph.NewFieldSpec(answermultichoices.FieldID, field.TypeInt))
	if ps := amcu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := amcu.mutation.Name(); ok {
		_spec.SetField(answermultichoices.FieldName, field.TypeString, value)
	}
	if value, ok := amcu.mutation.IsCorrect(); ok {
		_spec.SetField(answermultichoices.FieldIsCorrect, field.TypeBool, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, amcu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{answermultichoices.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	amcu.mutation.done = true
	return n, nil
}

// AnswerMultiChoicesUpdateOne is the builder for updating a single AnswerMultiChoices entity.
type AnswerMultiChoicesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AnswerMultiChoicesMutation
}

// SetName sets the "name" field.
func (amcuo *AnswerMultiChoicesUpdateOne) SetName(s string) *AnswerMultiChoicesUpdateOne {
	amcuo.mutation.SetName(s)
	return amcuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (amcuo *AnswerMultiChoicesUpdateOne) SetNillableName(s *string) *AnswerMultiChoicesUpdateOne {
	if s != nil {
		amcuo.SetName(*s)
	}
	return amcuo
}

// SetIsCorrect sets the "is_correct" field.
func (amcuo *AnswerMultiChoicesUpdateOne) SetIsCorrect(b bool) *AnswerMultiChoicesUpdateOne {
	amcuo.mutation.SetIsCorrect(b)
	return amcuo
}

// SetNillableIsCorrect sets the "is_correct" field if the given value is not nil.
func (amcuo *AnswerMultiChoicesUpdateOne) SetNillableIsCorrect(b *bool) *AnswerMultiChoicesUpdateOne {
	if b != nil {
		amcuo.SetIsCorrect(*b)
	}
	return amcuo
}

// Mutation returns the AnswerMultiChoicesMutation object of the builder.
func (amcuo *AnswerMultiChoicesUpdateOne) Mutation() *AnswerMultiChoicesMutation {
	return amcuo.mutation
}

// Where appends a list predicates to the AnswerMultiChoicesUpdate builder.
func (amcuo *AnswerMultiChoicesUpdateOne) Where(ps ...predicate.AnswerMultiChoices) *AnswerMultiChoicesUpdateOne {
	amcuo.mutation.Where(ps...)
	return amcuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (amcuo *AnswerMultiChoicesUpdateOne) Select(field string, fields ...string) *AnswerMultiChoicesUpdateOne {
	amcuo.fields = append([]string{field}, fields...)
	return amcuo
}

// Save executes the query and returns the updated AnswerMultiChoices entity.
func (amcuo *AnswerMultiChoicesUpdateOne) Save(ctx context.Context) (*AnswerMultiChoices, error) {
	return withHooks(ctx, amcuo.sqlSave, amcuo.mutation, amcuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (amcuo *AnswerMultiChoicesUpdateOne) SaveX(ctx context.Context) *AnswerMultiChoices {
	node, err := amcuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (amcuo *AnswerMultiChoicesUpdateOne) Exec(ctx context.Context) error {
	_, err := amcuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (amcuo *AnswerMultiChoicesUpdateOne) ExecX(ctx context.Context) {
	if err := amcuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (amcuo *AnswerMultiChoicesUpdateOne) check() error {
	if v, ok := amcuo.mutation.Name(); ok {
		if err := answermultichoices.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AnswerMultiChoices.name": %w`, err)}
		}
	}
	return nil
}

func (amcuo *AnswerMultiChoicesUpdateOne) sqlSave(ctx context.Context) (_node *AnswerMultiChoices, err error) {
	if err := amcuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(answermultichoices.Table, answermultichoices.Columns, sqlgraph.NewFieldSpec(answermultichoices.FieldID, field.TypeInt))
	id, ok := amcuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AnswerMultiChoices.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := amcuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, answermultichoices.FieldID)
		for _, f := range fields {
			if !answermultichoices.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != answermultichoices.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := amcuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := amcuo.mutation.Name(); ok {
		_spec.SetField(answermultichoices.FieldName, field.TypeString, value)
	}
	if value, ok := amcuo.mutation.IsCorrect(); ok {
		_spec.SetField(answermultichoices.FieldIsCorrect, field.TypeBool, value)
	}
	_node = &AnswerMultiChoices{config: amcuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, amcuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{answermultichoices.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	amcuo.mutation.done = true
	return _node, nil
}
