// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"study-pal-backend/ent/answertruth"
	"study-pal-backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AnswerTruthUpdate is the builder for updating AnswerTruth entities.
type AnswerTruthUpdate struct {
	config
	hooks    []Hook
	mutation *AnswerTruthMutation
}

// Where appends a list predicates to the AnswerTruthUpdate builder.
func (atu *AnswerTruthUpdate) Where(ps ...predicate.AnswerTruth) *AnswerTruthUpdate {
	atu.mutation.Where(ps...)
	return atu
}

// SetTruth sets the "truth" field.
func (atu *AnswerTruthUpdate) SetTruth(b bool) *AnswerTruthUpdate {
	atu.mutation.SetTruth(b)
	return atu
}

// SetNillableTruth sets the "truth" field if the given value is not nil.
func (atu *AnswerTruthUpdate) SetNillableTruth(b *bool) *AnswerTruthUpdate {
	if b != nil {
		atu.SetTruth(*b)
	}
	return atu
}

// Mutation returns the AnswerTruthMutation object of the builder.
func (atu *AnswerTruthUpdate) Mutation() *AnswerTruthMutation {
	return atu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (atu *AnswerTruthUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, atu.sqlSave, atu.mutation, atu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (atu *AnswerTruthUpdate) SaveX(ctx context.Context) int {
	affected, err := atu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (atu *AnswerTruthUpdate) Exec(ctx context.Context) error {
	_, err := atu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atu *AnswerTruthUpdate) ExecX(ctx context.Context) {
	if err := atu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (atu *AnswerTruthUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(answertruth.Table, answertruth.Columns, sqlgraph.NewFieldSpec(answertruth.FieldID, field.TypeInt))
	if ps := atu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := atu.mutation.Truth(); ok {
		_spec.SetField(answertruth.FieldTruth, field.TypeBool, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, atu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{answertruth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	atu.mutation.done = true
	return n, nil
}

// AnswerTruthUpdateOne is the builder for updating a single AnswerTruth entity.
type AnswerTruthUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AnswerTruthMutation
}

// SetTruth sets the "truth" field.
func (atuo *AnswerTruthUpdateOne) SetTruth(b bool) *AnswerTruthUpdateOne {
	atuo.mutation.SetTruth(b)
	return atuo
}

// SetNillableTruth sets the "truth" field if the given value is not nil.
func (atuo *AnswerTruthUpdateOne) SetNillableTruth(b *bool) *AnswerTruthUpdateOne {
	if b != nil {
		atuo.SetTruth(*b)
	}
	return atuo
}

// Mutation returns the AnswerTruthMutation object of the builder.
func (atuo *AnswerTruthUpdateOne) Mutation() *AnswerTruthMutation {
	return atuo.mutation
}

// Where appends a list predicates to the AnswerTruthUpdate builder.
func (atuo *AnswerTruthUpdateOne) Where(ps ...predicate.AnswerTruth) *AnswerTruthUpdateOne {
	atuo.mutation.Where(ps...)
	return atuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (atuo *AnswerTruthUpdateOne) Select(field string, fields ...string) *AnswerTruthUpdateOne {
	atuo.fields = append([]string{field}, fields...)
	return atuo
}

// Save executes the query and returns the updated AnswerTruth entity.
func (atuo *AnswerTruthUpdateOne) Save(ctx context.Context) (*AnswerTruth, error) {
	return withHooks(ctx, atuo.sqlSave, atuo.mutation, atuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (atuo *AnswerTruthUpdateOne) SaveX(ctx context.Context) *AnswerTruth {
	node, err := atuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (atuo *AnswerTruthUpdateOne) Exec(ctx context.Context) error {
	_, err := atuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atuo *AnswerTruthUpdateOne) ExecX(ctx context.Context) {
	if err := atuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (atuo *AnswerTruthUpdateOne) sqlSave(ctx context.Context) (_node *AnswerTruth, err error) {
	_spec := sqlgraph.NewUpdateSpec(answertruth.Table, answertruth.Columns, sqlgraph.NewFieldSpec(answertruth.FieldID, field.TypeInt))
	id, ok := atuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AnswerTruth.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := atuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, answertruth.FieldID)
		for _, f := range fields {
			if !answertruth.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != answertruth.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := atuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := atuo.mutation.Truth(); ok {
		_spec.SetField(answertruth.FieldTruth, field.TypeBool, value)
	}
	_node = &AnswerTruth{config: atuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, atuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{answertruth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	atuo.mutation.done = true
	return _node, nil
}
