// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"study-pal-backend/ent/descriptionproblem"
	"study-pal-backend/ent/workbook"
	"study-pal-backend/ent/workbookcategory"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// DescriptionProblem is the model entity for the DescriptionProblem schema.
type DescriptionProblem struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// CorrectStatement holds the value of the "correct_statement" field.
	CorrectStatement string `json:"correct_statement,omitempty"`
	// Statement holds the value of the "statement" field.
	Statement string `json:"statement,omitempty"`
	// WorkbookID holds the value of the "workbook_id" field.
	WorkbookID uuid.UUID `json:"workbook_id,omitempty"`
	// WorkbookCategoryID holds the value of the "workbook_category_id" field.
	WorkbookCategoryID *uuid.UUID `json:"workbook_category_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the DescriptionProblemQuery when eager-loading is set.
	Edges        DescriptionProblemEdges `json:"edges"`
	selectValues sql.SelectValues
}

// DescriptionProblemEdges holds the relations/edges for other nodes in the graph.
type DescriptionProblemEdges struct {
	// Workbook holds the value of the workbook edge.
	Workbook *Workbook `json:"workbook,omitempty"`
	// WorkbookCategory holds the value of the workbook_category edge.
	WorkbookCategory *WorkbookCategory `json:"workbook_category,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// WorkbookOrErr returns the Workbook value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DescriptionProblemEdges) WorkbookOrErr() (*Workbook, error) {
	if e.Workbook != nil {
		return e.Workbook, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: workbook.Label}
	}
	return nil, &NotLoadedError{edge: "workbook"}
}

// WorkbookCategoryOrErr returns the WorkbookCategory value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e DescriptionProblemEdges) WorkbookCategoryOrErr() (*WorkbookCategory, error) {
	if e.WorkbookCategory != nil {
		return e.WorkbookCategory, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: workbookcategory.Label}
	}
	return nil, &NotLoadedError{edge: "workbook_category"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DescriptionProblem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case descriptionproblem.FieldWorkbookCategoryID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case descriptionproblem.FieldCorrectStatement, descriptionproblem.FieldStatement:
			values[i] = new(sql.NullString)
		case descriptionproblem.FieldCreatedAt, descriptionproblem.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case descriptionproblem.FieldID, descriptionproblem.FieldWorkbookID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DescriptionProblem fields.
func (dp *DescriptionProblem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case descriptionproblem.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				dp.ID = *value
			}
		case descriptionproblem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				dp.CreatedAt = value.Time
			}
		case descriptionproblem.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				dp.UpdatedAt = value.Time
			}
		case descriptionproblem.FieldCorrectStatement:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field correct_statement", values[i])
			} else if value.Valid {
				dp.CorrectStatement = value.String
			}
		case descriptionproblem.FieldStatement:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field statement", values[i])
			} else if value.Valid {
				dp.Statement = value.String
			}
		case descriptionproblem.FieldWorkbookID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field workbook_id", values[i])
			} else if value != nil {
				dp.WorkbookID = *value
			}
		case descriptionproblem.FieldWorkbookCategoryID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field workbook_category_id", values[i])
			} else if value.Valid {
				dp.WorkbookCategoryID = new(uuid.UUID)
				*dp.WorkbookCategoryID = *value.S.(*uuid.UUID)
			}
		default:
			dp.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DescriptionProblem.
// This includes values selected through modifiers, order, etc.
func (dp *DescriptionProblem) Value(name string) (ent.Value, error) {
	return dp.selectValues.Get(name)
}

// QueryWorkbook queries the "workbook" edge of the DescriptionProblem entity.
func (dp *DescriptionProblem) QueryWorkbook() *WorkbookQuery {
	return NewDescriptionProblemClient(dp.config).QueryWorkbook(dp)
}

// QueryWorkbookCategory queries the "workbook_category" edge of the DescriptionProblem entity.
func (dp *DescriptionProblem) QueryWorkbookCategory() *WorkbookCategoryQuery {
	return NewDescriptionProblemClient(dp.config).QueryWorkbookCategory(dp)
}

// Update returns a builder for updating this DescriptionProblem.
// Note that you need to call DescriptionProblem.Unwrap() before calling this method if this DescriptionProblem
// was returned from a transaction, and the transaction was committed or rolled back.
func (dp *DescriptionProblem) Update() *DescriptionProblemUpdateOne {
	return NewDescriptionProblemClient(dp.config).UpdateOne(dp)
}

// Unwrap unwraps the DescriptionProblem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (dp *DescriptionProblem) Unwrap() *DescriptionProblem {
	_tx, ok := dp.config.driver.(*txDriver)
	if !ok {
		panic("ent: DescriptionProblem is not a transactional entity")
	}
	dp.config.driver = _tx.drv
	return dp
}

// String implements the fmt.Stringer.
func (dp *DescriptionProblem) String() string {
	var builder strings.Builder
	builder.WriteString("DescriptionProblem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", dp.ID))
	builder.WriteString("created_at=")
	builder.WriteString(dp.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(dp.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("correct_statement=")
	builder.WriteString(dp.CorrectStatement)
	builder.WriteString(", ")
	builder.WriteString("statement=")
	builder.WriteString(dp.Statement)
	builder.WriteString(", ")
	builder.WriteString("workbook_id=")
	builder.WriteString(fmt.Sprintf("%v", dp.WorkbookID))
	builder.WriteString(", ")
	if v := dp.WorkbookCategoryID; v != nil {
		builder.WriteString("workbook_category_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// DescriptionProblems is a parsable slice of DescriptionProblem.
type DescriptionProblems []*DescriptionProblem
