// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"study-pal-backend/ent/answerdescription"
	"study-pal-backend/ent/answertruth"
	"study-pal-backend/ent/answertype"
	"study-pal-backend/ent/problem"
	"study-pal-backend/ent/workbook"
	"study-pal-backend/ent/workbookcategory"
	"study-pal-backend/ent/workbookcategoryclassification"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Problem is the model entity for the Problem schema.
type Problem struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AnswerTypeID holds the value of the "answer_type_id" field.
	AnswerTypeID uuid.UUID `json:"answer_type_id,omitempty"`
	// Statement holds the value of the "statement" field.
	Statement string `json:"statement,omitempty"`
	// WorkbookID holds the value of the "workbook_id" field.
	WorkbookID uuid.UUID `json:"workbook_id,omitempty"`
	// WorkbookCategoryID holds the value of the "workbook_category_id" field.
	WorkbookCategoryID *uuid.UUID `json:"workbook_category_id,omitempty"`
	// WorkbookCategoryClassificationID holds the value of the "workbook_category_classification_id" field.
	WorkbookCategoryClassificationID *uuid.UUID `json:"workbook_category_classification_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProblemQuery when eager-loading is set.
	Edges        ProblemEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProblemEdges holds the relations/edges for other nodes in the graph.
type ProblemEdges struct {
	// AnswerType holds the value of the answer_type edge.
	AnswerType *AnswerType `json:"answer_type,omitempty"`
	// AnswerDescriptions holds the value of the answer_descriptions edge.
	AnswerDescriptions *AnswerDescription `json:"answer_descriptions,omitempty"`
	// AnswerMultiChoices holds the value of the answer_multi_choices edge.
	AnswerMultiChoices []*AnswerMultiChoices `json:"answer_multi_choices,omitempty"`
	// AnswerTruths holds the value of the answer_truths edge.
	AnswerTruths *AnswerTruth `json:"answer_truths,omitempty"`
	// Workbook holds the value of the workbook edge.
	Workbook *Workbook `json:"workbook,omitempty"`
	// WorkbookCategory holds the value of the workbook_category edge.
	WorkbookCategory *WorkbookCategory `json:"workbook_category,omitempty"`
	// WorkbookCategoryClassification holds the value of the workbook_category_classification edge.
	WorkbookCategoryClassification *WorkbookCategoryClassification `json:"workbook_category_classification,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
}

// AnswerTypeOrErr returns the AnswerType value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProblemEdges) AnswerTypeOrErr() (*AnswerType, error) {
	if e.AnswerType != nil {
		return e.AnswerType, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: answertype.Label}
	}
	return nil, &NotLoadedError{edge: "answer_type"}
}

// AnswerDescriptionsOrErr returns the AnswerDescriptions value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProblemEdges) AnswerDescriptionsOrErr() (*AnswerDescription, error) {
	if e.AnswerDescriptions != nil {
		return e.AnswerDescriptions, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: answerdescription.Label}
	}
	return nil, &NotLoadedError{edge: "answer_descriptions"}
}

// AnswerMultiChoicesOrErr returns the AnswerMultiChoices value or an error if the edge
// was not loaded in eager-loading.
func (e ProblemEdges) AnswerMultiChoicesOrErr() ([]*AnswerMultiChoices, error) {
	if e.loadedTypes[2] {
		return e.AnswerMultiChoices, nil
	}
	return nil, &NotLoadedError{edge: "answer_multi_choices"}
}

// AnswerTruthsOrErr returns the AnswerTruths value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProblemEdges) AnswerTruthsOrErr() (*AnswerTruth, error) {
	if e.AnswerTruths != nil {
		return e.AnswerTruths, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: answertruth.Label}
	}
	return nil, &NotLoadedError{edge: "answer_truths"}
}

// WorkbookOrErr returns the Workbook value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProblemEdges) WorkbookOrErr() (*Workbook, error) {
	if e.Workbook != nil {
		return e.Workbook, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: workbook.Label}
	}
	return nil, &NotLoadedError{edge: "workbook"}
}

// WorkbookCategoryOrErr returns the WorkbookCategory value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProblemEdges) WorkbookCategoryOrErr() (*WorkbookCategory, error) {
	if e.WorkbookCategory != nil {
		return e.WorkbookCategory, nil
	} else if e.loadedTypes[5] {
		return nil, &NotFoundError{label: workbookcategory.Label}
	}
	return nil, &NotLoadedError{edge: "workbook_category"}
}

// WorkbookCategoryClassificationOrErr returns the WorkbookCategoryClassification value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ProblemEdges) WorkbookCategoryClassificationOrErr() (*WorkbookCategoryClassification, error) {
	if e.WorkbookCategoryClassification != nil {
		return e.WorkbookCategoryClassification, nil
	} else if e.loadedTypes[6] {
		return nil, &NotFoundError{label: workbookcategoryclassification.Label}
	}
	return nil, &NotLoadedError{edge: "workbook_category_classification"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Problem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case problem.FieldWorkbookCategoryID, problem.FieldWorkbookCategoryClassificationID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case problem.FieldStatement:
			values[i] = new(sql.NullString)
		case problem.FieldCreatedAt, problem.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case problem.FieldID, problem.FieldAnswerTypeID, problem.FieldWorkbookID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Problem fields.
func (pr *Problem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case problem.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				pr.ID = *value
			}
		case problem.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pr.CreatedAt = value.Time
			}
		case problem.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				pr.UpdatedAt = value.Time
			}
		case problem.FieldAnswerTypeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field answer_type_id", values[i])
			} else if value != nil {
				pr.AnswerTypeID = *value
			}
		case problem.FieldStatement:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field statement", values[i])
			} else if value.Valid {
				pr.Statement = value.String
			}
		case problem.FieldWorkbookID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field workbook_id", values[i])
			} else if value != nil {
				pr.WorkbookID = *value
			}
		case problem.FieldWorkbookCategoryID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field workbook_category_id", values[i])
			} else if value.Valid {
				pr.WorkbookCategoryID = new(uuid.UUID)
				*pr.WorkbookCategoryID = *value.S.(*uuid.UUID)
			}
		case problem.FieldWorkbookCategoryClassificationID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field workbook_category_classification_id", values[i])
			} else if value.Valid {
				pr.WorkbookCategoryClassificationID = new(uuid.UUID)
				*pr.WorkbookCategoryClassificationID = *value.S.(*uuid.UUID)
			}
		default:
			pr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Problem.
// This includes values selected through modifiers, order, etc.
func (pr *Problem) Value(name string) (ent.Value, error) {
	return pr.selectValues.Get(name)
}

// QueryAnswerType queries the "answer_type" edge of the Problem entity.
func (pr *Problem) QueryAnswerType() *AnswerTypeQuery {
	return NewProblemClient(pr.config).QueryAnswerType(pr)
}

// QueryAnswerDescriptions queries the "answer_descriptions" edge of the Problem entity.
func (pr *Problem) QueryAnswerDescriptions() *AnswerDescriptionQuery {
	return NewProblemClient(pr.config).QueryAnswerDescriptions(pr)
}

// QueryAnswerMultiChoices queries the "answer_multi_choices" edge of the Problem entity.
func (pr *Problem) QueryAnswerMultiChoices() *AnswerMultiChoicesQuery {
	return NewProblemClient(pr.config).QueryAnswerMultiChoices(pr)
}

// QueryAnswerTruths queries the "answer_truths" edge of the Problem entity.
func (pr *Problem) QueryAnswerTruths() *AnswerTruthQuery {
	return NewProblemClient(pr.config).QueryAnswerTruths(pr)
}

// QueryWorkbook queries the "workbook" edge of the Problem entity.
func (pr *Problem) QueryWorkbook() *WorkbookQuery {
	return NewProblemClient(pr.config).QueryWorkbook(pr)
}

// QueryWorkbookCategory queries the "workbook_category" edge of the Problem entity.
func (pr *Problem) QueryWorkbookCategory() *WorkbookCategoryQuery {
	return NewProblemClient(pr.config).QueryWorkbookCategory(pr)
}

// QueryWorkbookCategoryClassification queries the "workbook_category_classification" edge of the Problem entity.
func (pr *Problem) QueryWorkbookCategoryClassification() *WorkbookCategoryClassificationQuery {
	return NewProblemClient(pr.config).QueryWorkbookCategoryClassification(pr)
}

// Update returns a builder for updating this Problem.
// Note that you need to call Problem.Unwrap() before calling this method if this Problem
// was returned from a transaction, and the transaction was committed or rolled back.
func (pr *Problem) Update() *ProblemUpdateOne {
	return NewProblemClient(pr.config).UpdateOne(pr)
}

// Unwrap unwraps the Problem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pr *Problem) Unwrap() *Problem {
	_tx, ok := pr.config.driver.(*txDriver)
	if !ok {
		panic("ent: Problem is not a transactional entity")
	}
	pr.config.driver = _tx.drv
	return pr
}

// String implements the fmt.Stringer.
func (pr *Problem) String() string {
	var builder strings.Builder
	builder.WriteString("Problem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pr.ID))
	builder.WriteString("created_at=")
	builder.WriteString(pr.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(pr.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("answer_type_id=")
	builder.WriteString(fmt.Sprintf("%v", pr.AnswerTypeID))
	builder.WriteString(", ")
	builder.WriteString("statement=")
	builder.WriteString(pr.Statement)
	builder.WriteString(", ")
	builder.WriteString("workbook_id=")
	builder.WriteString(fmt.Sprintf("%v", pr.WorkbookID))
	builder.WriteString(", ")
	if v := pr.WorkbookCategoryID; v != nil {
		builder.WriteString("workbook_category_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := pr.WorkbookCategoryClassificationID; v != nil {
		builder.WriteString("workbook_category_classification_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Problems is a parsable slice of Problem.
type Problems []*Problem
