// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"study-pal-backend/ent/role"
	"study-pal-backend/ent/user"
	"study-pal-backend/ent/workbook"
	"study-pal-backend/ent/workbookmember"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WorkbookMemberCreate is the builder for creating a WorkbookMember entity.
type WorkbookMemberCreate struct {
	config
	mutation *WorkbookMemberMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (wmc *WorkbookMemberCreate) SetCreatedAt(t time.Time) *WorkbookMemberCreate {
	wmc.mutation.SetCreatedAt(t)
	return wmc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wmc *WorkbookMemberCreate) SetNillableCreatedAt(t *time.Time) *WorkbookMemberCreate {
	if t != nil {
		wmc.SetCreatedAt(*t)
	}
	return wmc
}

// SetUpdatedAt sets the "updated_at" field.
func (wmc *WorkbookMemberCreate) SetUpdatedAt(t time.Time) *WorkbookMemberCreate {
	wmc.mutation.SetUpdatedAt(t)
	return wmc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (wmc *WorkbookMemberCreate) SetNillableUpdatedAt(t *time.Time) *WorkbookMemberCreate {
	if t != nil {
		wmc.SetUpdatedAt(*t)
	}
	return wmc
}

// SetRoleID sets the "role_id" field.
func (wmc *WorkbookMemberCreate) SetRoleID(u uuid.UUID) *WorkbookMemberCreate {
	wmc.mutation.SetRoleID(u)
	return wmc
}

// SetMemberID sets the "member_id" field.
func (wmc *WorkbookMemberCreate) SetMemberID(u uuid.UUID) *WorkbookMemberCreate {
	wmc.mutation.SetMemberID(u)
	return wmc
}

// SetWorkbookID sets the "workbook_id" field.
func (wmc *WorkbookMemberCreate) SetWorkbookID(u uuid.UUID) *WorkbookMemberCreate {
	wmc.mutation.SetWorkbookID(u)
	return wmc
}

// SetID sets the "id" field.
func (wmc *WorkbookMemberCreate) SetID(u uuid.UUID) *WorkbookMemberCreate {
	wmc.mutation.SetID(u)
	return wmc
}

// SetRole sets the "role" edge to the Role entity.
func (wmc *WorkbookMemberCreate) SetRole(r *Role) *WorkbookMemberCreate {
	return wmc.SetRoleID(r.ID)
}

// SetMember sets the "member" edge to the User entity.
func (wmc *WorkbookMemberCreate) SetMember(u *User) *WorkbookMemberCreate {
	return wmc.SetMemberID(u.ID)
}

// SetWorkbook sets the "workbook" edge to the Workbook entity.
func (wmc *WorkbookMemberCreate) SetWorkbook(w *Workbook) *WorkbookMemberCreate {
	return wmc.SetWorkbookID(w.ID)
}

// Mutation returns the WorkbookMemberMutation object of the builder.
func (wmc *WorkbookMemberCreate) Mutation() *WorkbookMemberMutation {
	return wmc.mutation
}

// Save creates the WorkbookMember in the database.
func (wmc *WorkbookMemberCreate) Save(ctx context.Context) (*WorkbookMember, error) {
	wmc.defaults()
	return withHooks(ctx, wmc.sqlSave, wmc.mutation, wmc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (wmc *WorkbookMemberCreate) SaveX(ctx context.Context) *WorkbookMember {
	v, err := wmc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wmc *WorkbookMemberCreate) Exec(ctx context.Context) error {
	_, err := wmc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wmc *WorkbookMemberCreate) ExecX(ctx context.Context) {
	if err := wmc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wmc *WorkbookMemberCreate) defaults() {
	if _, ok := wmc.mutation.CreatedAt(); !ok {
		v := workbookmember.DefaultCreatedAt()
		wmc.mutation.SetCreatedAt(v)
	}
	if _, ok := wmc.mutation.UpdatedAt(); !ok {
		v := workbookmember.DefaultUpdatedAt()
		wmc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wmc *WorkbookMemberCreate) check() error {
	if _, ok := wmc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "WorkbookMember.created_at"`)}
	}
	if _, ok := wmc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "WorkbookMember.updated_at"`)}
	}
	if _, ok := wmc.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "WorkbookMember.role_id"`)}
	}
	if _, ok := wmc.mutation.MemberID(); !ok {
		return &ValidationError{Name: "member_id", err: errors.New(`ent: missing required field "WorkbookMember.member_id"`)}
	}
	if _, ok := wmc.mutation.WorkbookID(); !ok {
		return &ValidationError{Name: "workbook_id", err: errors.New(`ent: missing required field "WorkbookMember.workbook_id"`)}
	}
	if len(wmc.mutation.RoleIDs()) == 0 {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required edge "WorkbookMember.role"`)}
	}
	if len(wmc.mutation.MemberIDs()) == 0 {
		return &ValidationError{Name: "member", err: errors.New(`ent: missing required edge "WorkbookMember.member"`)}
	}
	if len(wmc.mutation.WorkbookIDs()) == 0 {
		return &ValidationError{Name: "workbook", err: errors.New(`ent: missing required edge "WorkbookMember.workbook"`)}
	}
	return nil
}

func (wmc *WorkbookMemberCreate) sqlSave(ctx context.Context) (*WorkbookMember, error) {
	if err := wmc.check(); err != nil {
		return nil, err
	}
	_node, _spec := wmc.createSpec()
	if err := sqlgraph.CreateNode(ctx, wmc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	wmc.mutation.id = &_node.ID
	wmc.mutation.done = true
	return _node, nil
}

func (wmc *WorkbookMemberCreate) createSpec() (*WorkbookMember, *sqlgraph.CreateSpec) {
	var (
		_node = &WorkbookMember{config: wmc.config}
		_spec = sqlgraph.NewCreateSpec(workbookmember.Table, sqlgraph.NewFieldSpec(workbookmember.FieldID, field.TypeUUID))
	)
	if id, ok := wmc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := wmc.mutation.CreatedAt(); ok {
		_spec.SetField(workbookmember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := wmc.mutation.UpdatedAt(); ok {
		_spec.SetField(workbookmember.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := wmc.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workbookmember.RoleTable,
			Columns: []string{workbookmember.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := wmc.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workbookmember.MemberTable,
			Columns: []string{workbookmember.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MemberID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := wmc.mutation.WorkbookIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workbookmember.WorkbookTable,
			Columns: []string{workbookmember.WorkbookColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workbook.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkbookID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WorkbookMemberCreateBulk is the builder for creating many WorkbookMember entities in bulk.
type WorkbookMemberCreateBulk struct {
	config
	err      error
	builders []*WorkbookMemberCreate
}

// Save creates the WorkbookMember entities in the database.
func (wmcb *WorkbookMemberCreateBulk) Save(ctx context.Context) ([]*WorkbookMember, error) {
	if wmcb.err != nil {
		return nil, wmcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(wmcb.builders))
	nodes := make([]*WorkbookMember, len(wmcb.builders))
	mutators := make([]Mutator, len(wmcb.builders))
	for i := range wmcb.builders {
		func(i int, root context.Context) {
			builder := wmcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WorkbookMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, wmcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, wmcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, wmcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (wmcb *WorkbookMemberCreateBulk) SaveX(ctx context.Context) []*WorkbookMember {
	v, err := wmcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (wmcb *WorkbookMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := wmcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wmcb *WorkbookMemberCreateBulk) ExecX(ctx context.Context) {
	if err := wmcb.Exec(ctx); err != nil {
		panic(err)
	}
}
