// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"study-pal-backend/ent/predicate"
	"study-pal-backend/ent/problem"
	"study-pal-backend/ent/workbookcategorydetail"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WorkbookCategoryDetailUpdate is the builder for updating WorkbookCategoryDetail entities.
type WorkbookCategoryDetailUpdate struct {
	config
	hooks    []Hook
	mutation *WorkbookCategoryDetailMutation
}

// Where appends a list predicates to the WorkbookCategoryDetailUpdate builder.
func (wcdu *WorkbookCategoryDetailUpdate) Where(ps ...predicate.WorkbookCategoryDetail) *WorkbookCategoryDetailUpdate {
	wcdu.mutation.Where(ps...)
	return wcdu
}

// SetCreatedAt sets the "created_at" field.
func (wcdu *WorkbookCategoryDetailUpdate) SetCreatedAt(t time.Time) *WorkbookCategoryDetailUpdate {
	wcdu.mutation.SetCreatedAt(t)
	return wcdu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wcdu *WorkbookCategoryDetailUpdate) SetNillableCreatedAt(t *time.Time) *WorkbookCategoryDetailUpdate {
	if t != nil {
		wcdu.SetCreatedAt(*t)
	}
	return wcdu
}

// SetUpdatedAt sets the "updated_at" field.
func (wcdu *WorkbookCategoryDetailUpdate) SetUpdatedAt(t time.Time) *WorkbookCategoryDetailUpdate {
	wcdu.mutation.SetUpdatedAt(t)
	return wcdu
}

// SetName sets the "name" field.
func (wcdu *WorkbookCategoryDetailUpdate) SetName(s string) *WorkbookCategoryDetailUpdate {
	wcdu.mutation.SetName(s)
	return wcdu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wcdu *WorkbookCategoryDetailUpdate) SetNillableName(s *string) *WorkbookCategoryDetailUpdate {
	if s != nil {
		wcdu.SetName(*s)
	}
	return wcdu
}

// SetWorkbookCategoryID sets the "workbook_category_id" field.
func (wcdu *WorkbookCategoryDetailUpdate) SetWorkbookCategoryID(u uuid.UUID) *WorkbookCategoryDetailUpdate {
	wcdu.mutation.SetWorkbookCategoryID(u)
	return wcdu
}

// SetNillableWorkbookCategoryID sets the "workbook_category_id" field if the given value is not nil.
func (wcdu *WorkbookCategoryDetailUpdate) SetNillableWorkbookCategoryID(u *uuid.UUID) *WorkbookCategoryDetailUpdate {
	if u != nil {
		wcdu.SetWorkbookCategoryID(*u)
	}
	return wcdu
}

// AddProblemIDs adds the "problems" edge to the Problem entity by IDs.
func (wcdu *WorkbookCategoryDetailUpdate) AddProblemIDs(ids ...uuid.UUID) *WorkbookCategoryDetailUpdate {
	wcdu.mutation.AddProblemIDs(ids...)
	return wcdu
}

// AddProblems adds the "problems" edges to the Problem entity.
func (wcdu *WorkbookCategoryDetailUpdate) AddProblems(p ...*Problem) *WorkbookCategoryDetailUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return wcdu.AddProblemIDs(ids...)
}

// Mutation returns the WorkbookCategoryDetailMutation object of the builder.
func (wcdu *WorkbookCategoryDetailUpdate) Mutation() *WorkbookCategoryDetailMutation {
	return wcdu.mutation
}

// ClearProblems clears all "problems" edges to the Problem entity.
func (wcdu *WorkbookCategoryDetailUpdate) ClearProblems() *WorkbookCategoryDetailUpdate {
	wcdu.mutation.ClearProblems()
	return wcdu
}

// RemoveProblemIDs removes the "problems" edge to Problem entities by IDs.
func (wcdu *WorkbookCategoryDetailUpdate) RemoveProblemIDs(ids ...uuid.UUID) *WorkbookCategoryDetailUpdate {
	wcdu.mutation.RemoveProblemIDs(ids...)
	return wcdu
}

// RemoveProblems removes "problems" edges to Problem entities.
func (wcdu *WorkbookCategoryDetailUpdate) RemoveProblems(p ...*Problem) *WorkbookCategoryDetailUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return wcdu.RemoveProblemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (wcdu *WorkbookCategoryDetailUpdate) Save(ctx context.Context) (int, error) {
	wcdu.defaults()
	return withHooks(ctx, wcdu.sqlSave, wcdu.mutation, wcdu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wcdu *WorkbookCategoryDetailUpdate) SaveX(ctx context.Context) int {
	affected, err := wcdu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (wcdu *WorkbookCategoryDetailUpdate) Exec(ctx context.Context) error {
	_, err := wcdu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wcdu *WorkbookCategoryDetailUpdate) ExecX(ctx context.Context) {
	if err := wcdu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wcdu *WorkbookCategoryDetailUpdate) defaults() {
	if _, ok := wcdu.mutation.UpdatedAt(); !ok {
		v := workbookcategorydetail.UpdateDefaultUpdatedAt()
		wcdu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wcdu *WorkbookCategoryDetailUpdate) check() error {
	if v, ok := wcdu.mutation.Name(); ok {
		if err := workbookcategorydetail.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "WorkbookCategoryDetail.name": %w`, err)}
		}
	}
	return nil
}

func (wcdu *WorkbookCategoryDetailUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := wcdu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(workbookcategorydetail.Table, workbookcategorydetail.Columns, sqlgraph.NewFieldSpec(workbookcategorydetail.FieldID, field.TypeUUID))
	if ps := wcdu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wcdu.mutation.CreatedAt(); ok {
		_spec.SetField(workbookcategorydetail.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := wcdu.mutation.UpdatedAt(); ok {
		_spec.SetField(workbookcategorydetail.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := wcdu.mutation.Name(); ok {
		_spec.SetField(workbookcategorydetail.FieldName, field.TypeString, value)
	}
	if value, ok := wcdu.mutation.WorkbookCategoryID(); ok {
		_spec.SetField(workbookcategorydetail.FieldWorkbookCategoryID, field.TypeUUID, value)
	}
	if wcdu.mutation.ProblemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workbookcategorydetail.ProblemsTable,
			Columns: []string{workbookcategorydetail.ProblemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wcdu.mutation.RemovedProblemsIDs(); len(nodes) > 0 && !wcdu.mutation.ProblemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workbookcategorydetail.ProblemsTable,
			Columns: []string{workbookcategorydetail.ProblemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wcdu.mutation.ProblemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workbookcategorydetail.ProblemsTable,
			Columns: []string{workbookcategorydetail.ProblemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, wcdu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workbookcategorydetail.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	wcdu.mutation.done = true
	return n, nil
}

// WorkbookCategoryDetailUpdateOne is the builder for updating a single WorkbookCategoryDetail entity.
type WorkbookCategoryDetailUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkbookCategoryDetailMutation
}

// SetCreatedAt sets the "created_at" field.
func (wcduo *WorkbookCategoryDetailUpdateOne) SetCreatedAt(t time.Time) *WorkbookCategoryDetailUpdateOne {
	wcduo.mutation.SetCreatedAt(t)
	return wcduo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (wcduo *WorkbookCategoryDetailUpdateOne) SetNillableCreatedAt(t *time.Time) *WorkbookCategoryDetailUpdateOne {
	if t != nil {
		wcduo.SetCreatedAt(*t)
	}
	return wcduo
}

// SetUpdatedAt sets the "updated_at" field.
func (wcduo *WorkbookCategoryDetailUpdateOne) SetUpdatedAt(t time.Time) *WorkbookCategoryDetailUpdateOne {
	wcduo.mutation.SetUpdatedAt(t)
	return wcduo
}

// SetName sets the "name" field.
func (wcduo *WorkbookCategoryDetailUpdateOne) SetName(s string) *WorkbookCategoryDetailUpdateOne {
	wcduo.mutation.SetName(s)
	return wcduo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (wcduo *WorkbookCategoryDetailUpdateOne) SetNillableName(s *string) *WorkbookCategoryDetailUpdateOne {
	if s != nil {
		wcduo.SetName(*s)
	}
	return wcduo
}

// SetWorkbookCategoryID sets the "workbook_category_id" field.
func (wcduo *WorkbookCategoryDetailUpdateOne) SetWorkbookCategoryID(u uuid.UUID) *WorkbookCategoryDetailUpdateOne {
	wcduo.mutation.SetWorkbookCategoryID(u)
	return wcduo
}

// SetNillableWorkbookCategoryID sets the "workbook_category_id" field if the given value is not nil.
func (wcduo *WorkbookCategoryDetailUpdateOne) SetNillableWorkbookCategoryID(u *uuid.UUID) *WorkbookCategoryDetailUpdateOne {
	if u != nil {
		wcduo.SetWorkbookCategoryID(*u)
	}
	return wcduo
}

// AddProblemIDs adds the "problems" edge to the Problem entity by IDs.
func (wcduo *WorkbookCategoryDetailUpdateOne) AddProblemIDs(ids ...uuid.UUID) *WorkbookCategoryDetailUpdateOne {
	wcduo.mutation.AddProblemIDs(ids...)
	return wcduo
}

// AddProblems adds the "problems" edges to the Problem entity.
func (wcduo *WorkbookCategoryDetailUpdateOne) AddProblems(p ...*Problem) *WorkbookCategoryDetailUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return wcduo.AddProblemIDs(ids...)
}

// Mutation returns the WorkbookCategoryDetailMutation object of the builder.
func (wcduo *WorkbookCategoryDetailUpdateOne) Mutation() *WorkbookCategoryDetailMutation {
	return wcduo.mutation
}

// ClearProblems clears all "problems" edges to the Problem entity.
func (wcduo *WorkbookCategoryDetailUpdateOne) ClearProblems() *WorkbookCategoryDetailUpdateOne {
	wcduo.mutation.ClearProblems()
	return wcduo
}

// RemoveProblemIDs removes the "problems" edge to Problem entities by IDs.
func (wcduo *WorkbookCategoryDetailUpdateOne) RemoveProblemIDs(ids ...uuid.UUID) *WorkbookCategoryDetailUpdateOne {
	wcduo.mutation.RemoveProblemIDs(ids...)
	return wcduo
}

// RemoveProblems removes "problems" edges to Problem entities.
func (wcduo *WorkbookCategoryDetailUpdateOne) RemoveProblems(p ...*Problem) *WorkbookCategoryDetailUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return wcduo.RemoveProblemIDs(ids...)
}

// Where appends a list predicates to the WorkbookCategoryDetailUpdate builder.
func (wcduo *WorkbookCategoryDetailUpdateOne) Where(ps ...predicate.WorkbookCategoryDetail) *WorkbookCategoryDetailUpdateOne {
	wcduo.mutation.Where(ps...)
	return wcduo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (wcduo *WorkbookCategoryDetailUpdateOne) Select(field string, fields ...string) *WorkbookCategoryDetailUpdateOne {
	wcduo.fields = append([]string{field}, fields...)
	return wcduo
}

// Save executes the query and returns the updated WorkbookCategoryDetail entity.
func (wcduo *WorkbookCategoryDetailUpdateOne) Save(ctx context.Context) (*WorkbookCategoryDetail, error) {
	wcduo.defaults()
	return withHooks(ctx, wcduo.sqlSave, wcduo.mutation, wcduo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (wcduo *WorkbookCategoryDetailUpdateOne) SaveX(ctx context.Context) *WorkbookCategoryDetail {
	node, err := wcduo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (wcduo *WorkbookCategoryDetailUpdateOne) Exec(ctx context.Context) error {
	_, err := wcduo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (wcduo *WorkbookCategoryDetailUpdateOne) ExecX(ctx context.Context) {
	if err := wcduo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (wcduo *WorkbookCategoryDetailUpdateOne) defaults() {
	if _, ok := wcduo.mutation.UpdatedAt(); !ok {
		v := workbookcategorydetail.UpdateDefaultUpdatedAt()
		wcduo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (wcduo *WorkbookCategoryDetailUpdateOne) check() error {
	if v, ok := wcduo.mutation.Name(); ok {
		if err := workbookcategorydetail.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "WorkbookCategoryDetail.name": %w`, err)}
		}
	}
	return nil
}

func (wcduo *WorkbookCategoryDetailUpdateOne) sqlSave(ctx context.Context) (_node *WorkbookCategoryDetail, err error) {
	if err := wcduo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workbookcategorydetail.Table, workbookcategorydetail.Columns, sqlgraph.NewFieldSpec(workbookcategorydetail.FieldID, field.TypeUUID))
	id, ok := wcduo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WorkbookCategoryDetail.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := wcduo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workbookcategorydetail.FieldID)
		for _, f := range fields {
			if !workbookcategorydetail.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workbookcategorydetail.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := wcduo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := wcduo.mutation.CreatedAt(); ok {
		_spec.SetField(workbookcategorydetail.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := wcduo.mutation.UpdatedAt(); ok {
		_spec.SetField(workbookcategorydetail.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := wcduo.mutation.Name(); ok {
		_spec.SetField(workbookcategorydetail.FieldName, field.TypeString, value)
	}
	if value, ok := wcduo.mutation.WorkbookCategoryID(); ok {
		_spec.SetField(workbookcategorydetail.FieldWorkbookCategoryID, field.TypeUUID, value)
	}
	if wcduo.mutation.ProblemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workbookcategorydetail.ProblemsTable,
			Columns: []string{workbookcategorydetail.ProblemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wcduo.mutation.RemovedProblemsIDs(); len(nodes) > 0 && !wcduo.mutation.ProblemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workbookcategorydetail.ProblemsTable,
			Columns: []string{workbookcategorydetail.ProblemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := wcduo.mutation.ProblemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workbookcategorydetail.ProblemsTable,
			Columns: []string{workbookcategorydetail.ProblemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(problem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &WorkbookCategoryDetail{config: wcduo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, wcduo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workbookcategorydetail.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	wcduo.mutation.done = true
	return _node, nil
}
