// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"study-pal-backend/ent/predicate"
	"study-pal-backend/ent/problem"
	"study-pal-backend/ent/workbook"
	"study-pal-backend/ent/workbookcategory"
	"study-pal-backend/ent/workbookcategoryclosure"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkbookCategoryQuery is the builder for querying WorkbookCategory entities.
type WorkbookCategoryQuery struct {
	config
	ctx                          *QueryContext
	order                        []workbookcategory.OrderOption
	inters                       []Interceptor
	predicates                   []predicate.WorkbookCategory
	withProblems                 *ProblemQuery
	withWorkbook                 *WorkbookQuery
	withWorkbookCategoryClosures *WorkbookCategoryClosureQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WorkbookCategoryQuery builder.
func (wcq *WorkbookCategoryQuery) Where(ps ...predicate.WorkbookCategory) *WorkbookCategoryQuery {
	wcq.predicates = append(wcq.predicates, ps...)
	return wcq
}

// Limit the number of records to be returned by this query.
func (wcq *WorkbookCategoryQuery) Limit(limit int) *WorkbookCategoryQuery {
	wcq.ctx.Limit = &limit
	return wcq
}

// Offset to start from.
func (wcq *WorkbookCategoryQuery) Offset(offset int) *WorkbookCategoryQuery {
	wcq.ctx.Offset = &offset
	return wcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wcq *WorkbookCategoryQuery) Unique(unique bool) *WorkbookCategoryQuery {
	wcq.ctx.Unique = &unique
	return wcq
}

// Order specifies how the records should be ordered.
func (wcq *WorkbookCategoryQuery) Order(o ...workbookcategory.OrderOption) *WorkbookCategoryQuery {
	wcq.order = append(wcq.order, o...)
	return wcq
}

// QueryProblems chains the current query on the "problems" edge.
func (wcq *WorkbookCategoryQuery) QueryProblems() *ProblemQuery {
	query := (&ProblemClient{config: wcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workbookcategory.Table, workbookcategory.FieldID, selector),
			sqlgraph.To(problem.Table, problem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, workbookcategory.ProblemsTable, workbookcategory.ProblemsColumn),
		)
		fromU = sqlgraph.SetNeighbors(wcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWorkbook chains the current query on the "workbook" edge.
func (wcq *WorkbookCategoryQuery) QueryWorkbook() *WorkbookQuery {
	query := (&WorkbookClient{config: wcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workbookcategory.Table, workbookcategory.FieldID, selector),
			sqlgraph.To(workbook.Table, workbook.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, workbookcategory.WorkbookTable, workbookcategory.WorkbookColumn),
		)
		fromU = sqlgraph.SetNeighbors(wcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWorkbookCategoryClosures chains the current query on the "workbook_category_closures" edge.
func (wcq *WorkbookCategoryQuery) QueryWorkbookCategoryClosures() *WorkbookCategoryClosureQuery {
	query := (&WorkbookCategoryClosureClient{config: wcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workbookcategory.Table, workbookcategory.FieldID, selector),
			sqlgraph.To(workbookcategoryclosure.Table, workbookcategoryclosure.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, workbookcategory.WorkbookCategoryClosuresTable, workbookcategory.WorkbookCategoryClosuresColumn),
		)
		fromU = sqlgraph.SetNeighbors(wcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WorkbookCategory entity from the query.
// Returns a *NotFoundError when no WorkbookCategory was found.
func (wcq *WorkbookCategoryQuery) First(ctx context.Context) (*WorkbookCategory, error) {
	nodes, err := wcq.Limit(1).All(setContextOp(ctx, wcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{workbookcategory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wcq *WorkbookCategoryQuery) FirstX(ctx context.Context) *WorkbookCategory {
	node, err := wcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WorkbookCategory ID from the query.
// Returns a *NotFoundError when no WorkbookCategory ID was found.
func (wcq *WorkbookCategoryQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wcq.Limit(1).IDs(setContextOp(ctx, wcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{workbookcategory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wcq *WorkbookCategoryQuery) FirstIDX(ctx context.Context) int {
	id, err := wcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WorkbookCategory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WorkbookCategory entity is found.
// Returns a *NotFoundError when no WorkbookCategory entities are found.
func (wcq *WorkbookCategoryQuery) Only(ctx context.Context) (*WorkbookCategory, error) {
	nodes, err := wcq.Limit(2).All(setContextOp(ctx, wcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{workbookcategory.Label}
	default:
		return nil, &NotSingularError{workbookcategory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wcq *WorkbookCategoryQuery) OnlyX(ctx context.Context) *WorkbookCategory {
	node, err := wcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WorkbookCategory ID in the query.
// Returns a *NotSingularError when more than one WorkbookCategory ID is found.
// Returns a *NotFoundError when no entities are found.
func (wcq *WorkbookCategoryQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wcq.Limit(2).IDs(setContextOp(ctx, wcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{workbookcategory.Label}
	default:
		err = &NotSingularError{workbookcategory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wcq *WorkbookCategoryQuery) OnlyIDX(ctx context.Context) int {
	id, err := wcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WorkbookCategories.
func (wcq *WorkbookCategoryQuery) All(ctx context.Context) ([]*WorkbookCategory, error) {
	ctx = setContextOp(ctx, wcq.ctx, ent.OpQueryAll)
	if err := wcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WorkbookCategory, *WorkbookCategoryQuery]()
	return withInterceptors[[]*WorkbookCategory](ctx, wcq, qr, wcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wcq *WorkbookCategoryQuery) AllX(ctx context.Context) []*WorkbookCategory {
	nodes, err := wcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WorkbookCategory IDs.
func (wcq *WorkbookCategoryQuery) IDs(ctx context.Context) (ids []int, err error) {
	if wcq.ctx.Unique == nil && wcq.path != nil {
		wcq.Unique(true)
	}
	ctx = setContextOp(ctx, wcq.ctx, ent.OpQueryIDs)
	if err = wcq.Select(workbookcategory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wcq *WorkbookCategoryQuery) IDsX(ctx context.Context) []int {
	ids, err := wcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wcq *WorkbookCategoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wcq.ctx, ent.OpQueryCount)
	if err := wcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wcq, querierCount[*WorkbookCategoryQuery](), wcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wcq *WorkbookCategoryQuery) CountX(ctx context.Context) int {
	count, err := wcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wcq *WorkbookCategoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wcq.ctx, ent.OpQueryExist)
	switch _, err := wcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wcq *WorkbookCategoryQuery) ExistX(ctx context.Context) bool {
	exist, err := wcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WorkbookCategoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wcq *WorkbookCategoryQuery) Clone() *WorkbookCategoryQuery {
	if wcq == nil {
		return nil
	}
	return &WorkbookCategoryQuery{
		config:                       wcq.config,
		ctx:                          wcq.ctx.Clone(),
		order:                        append([]workbookcategory.OrderOption{}, wcq.order...),
		inters:                       append([]Interceptor{}, wcq.inters...),
		predicates:                   append([]predicate.WorkbookCategory{}, wcq.predicates...),
		withProblems:                 wcq.withProblems.Clone(),
		withWorkbook:                 wcq.withWorkbook.Clone(),
		withWorkbookCategoryClosures: wcq.withWorkbookCategoryClosures.Clone(),
		// clone intermediate query.
		sql:  wcq.sql.Clone(),
		path: wcq.path,
	}
}

// WithProblems tells the query-builder to eager-load the nodes that are connected to
// the "problems" edge. The optional arguments are used to configure the query builder of the edge.
func (wcq *WorkbookCategoryQuery) WithProblems(opts ...func(*ProblemQuery)) *WorkbookCategoryQuery {
	query := (&ProblemClient{config: wcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wcq.withProblems = query
	return wcq
}

// WithWorkbook tells the query-builder to eager-load the nodes that are connected to
// the "workbook" edge. The optional arguments are used to configure the query builder of the edge.
func (wcq *WorkbookCategoryQuery) WithWorkbook(opts ...func(*WorkbookQuery)) *WorkbookCategoryQuery {
	query := (&WorkbookClient{config: wcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wcq.withWorkbook = query
	return wcq
}

// WithWorkbookCategoryClosures tells the query-builder to eager-load the nodes that are connected to
// the "workbook_category_closures" edge. The optional arguments are used to configure the query builder of the edge.
func (wcq *WorkbookCategoryQuery) WithWorkbookCategoryClosures(opts ...func(*WorkbookCategoryClosureQuery)) *WorkbookCategoryQuery {
	query := (&WorkbookCategoryClosureClient{config: wcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wcq.withWorkbookCategoryClosures = query
	return wcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WorkbookCategory.Query().
//		GroupBy(workbookcategory.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wcq *WorkbookCategoryQuery) GroupBy(field string, fields ...string) *WorkbookCategoryGroupBy {
	wcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WorkbookCategoryGroupBy{build: wcq}
	grbuild.flds = &wcq.ctx.Fields
	grbuild.label = workbookcategory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.WorkbookCategory.Query().
//		Select(workbookcategory.FieldCreatedAt).
//		Scan(ctx, &v)
func (wcq *WorkbookCategoryQuery) Select(fields ...string) *WorkbookCategorySelect {
	wcq.ctx.Fields = append(wcq.ctx.Fields, fields...)
	sbuild := &WorkbookCategorySelect{WorkbookCategoryQuery: wcq}
	sbuild.label = workbookcategory.Label
	sbuild.flds, sbuild.scan = &wcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WorkbookCategorySelect configured with the given aggregations.
func (wcq *WorkbookCategoryQuery) Aggregate(fns ...AggregateFunc) *WorkbookCategorySelect {
	return wcq.Select().Aggregate(fns...)
}

func (wcq *WorkbookCategoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wcq); err != nil {
				return err
			}
		}
	}
	for _, f := range wcq.ctx.Fields {
		if !workbookcategory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wcq.path != nil {
		prev, err := wcq.path(ctx)
		if err != nil {
			return err
		}
		wcq.sql = prev
	}
	return nil
}

func (wcq *WorkbookCategoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WorkbookCategory, error) {
	var (
		nodes       = []*WorkbookCategory{}
		_spec       = wcq.querySpec()
		loadedTypes = [3]bool{
			wcq.withProblems != nil,
			wcq.withWorkbook != nil,
			wcq.withWorkbookCategoryClosures != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WorkbookCategory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WorkbookCategory{config: wcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := wcq.withProblems; query != nil {
		if err := wcq.loadProblems(ctx, query, nodes,
			func(n *WorkbookCategory) { n.Edges.Problems = []*Problem{} },
			func(n *WorkbookCategory, e *Problem) { n.Edges.Problems = append(n.Edges.Problems, e) }); err != nil {
			return nil, err
		}
	}
	if query := wcq.withWorkbook; query != nil {
		if err := wcq.loadWorkbook(ctx, query, nodes, nil,
			func(n *WorkbookCategory, e *Workbook) { n.Edges.Workbook = e }); err != nil {
			return nil, err
		}
	}
	if query := wcq.withWorkbookCategoryClosures; query != nil {
		if err := wcq.loadWorkbookCategoryClosures(ctx, query, nodes,
			func(n *WorkbookCategory) { n.Edges.WorkbookCategoryClosures = []*WorkbookCategoryClosure{} },
			func(n *WorkbookCategory, e *WorkbookCategoryClosure) {
				n.Edges.WorkbookCategoryClosures = append(n.Edges.WorkbookCategoryClosures, e)
			}); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (wcq *WorkbookCategoryQuery) loadProblems(ctx context.Context, query *ProblemQuery, nodes []*WorkbookCategory, init func(*WorkbookCategory), assign func(*WorkbookCategory, *Problem)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*WorkbookCategory)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Problem(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(workbookcategory.ProblemsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.workbook_category_problems
		if fk == nil {
			return fmt.Errorf(`foreign-key "workbook_category_problems" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "workbook_category_problems" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (wcq *WorkbookCategoryQuery) loadWorkbook(ctx context.Context, query *WorkbookQuery, nodes []*WorkbookCategory, init func(*WorkbookCategory), assign func(*WorkbookCategory, *Workbook)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*WorkbookCategory)
	for i := range nodes {
		fk := nodes[i].WorkbookID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(workbook.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "workbook_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (wcq *WorkbookCategoryQuery) loadWorkbookCategoryClosures(ctx context.Context, query *WorkbookCategoryClosureQuery, nodes []*WorkbookCategory, init func(*WorkbookCategory), assign func(*WorkbookCategory, *WorkbookCategoryClosure)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*WorkbookCategory)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.WorkbookCategoryClosure(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(workbookcategory.WorkbookCategoryClosuresColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.workbook_category_workbook_category_closures
		if fk == nil {
			return fmt.Errorf(`foreign-key "workbook_category_workbook_category_closures" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "workbook_category_workbook_category_closures" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (wcq *WorkbookCategoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wcq.querySpec()
	_spec.Node.Columns = wcq.ctx.Fields
	if len(wcq.ctx.Fields) > 0 {
		_spec.Unique = wcq.ctx.Unique != nil && *wcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wcq.driver, _spec)
}

func (wcq *WorkbookCategoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(workbookcategory.Table, workbookcategory.Columns, sqlgraph.NewFieldSpec(workbookcategory.FieldID, field.TypeInt))
	_spec.From = wcq.sql
	if unique := wcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wcq.path != nil {
		_spec.Unique = true
	}
	if fields := wcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workbookcategory.FieldID)
		for i := range fields {
			if fields[i] != workbookcategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if wcq.withWorkbook != nil {
			_spec.Node.AddColumnOnce(workbookcategory.FieldWorkbookID)
		}
	}
	if ps := wcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wcq *WorkbookCategoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wcq.driver.Dialect())
	t1 := builder.Table(workbookcategory.Table)
	columns := wcq.ctx.Fields
	if len(columns) == 0 {
		columns = workbookcategory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wcq.sql != nil {
		selector = wcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wcq.ctx.Unique != nil && *wcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wcq.predicates {
		p(selector)
	}
	for _, p := range wcq.order {
		p(selector)
	}
	if offset := wcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WorkbookCategoryGroupBy is the group-by builder for WorkbookCategory entities.
type WorkbookCategoryGroupBy struct {
	selector
	build *WorkbookCategoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wcgb *WorkbookCategoryGroupBy) Aggregate(fns ...AggregateFunc) *WorkbookCategoryGroupBy {
	wcgb.fns = append(wcgb.fns, fns...)
	return wcgb
}

// Scan applies the selector query and scans the result into the given value.
func (wcgb *WorkbookCategoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wcgb.build.ctx, ent.OpQueryGroupBy)
	if err := wcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkbookCategoryQuery, *WorkbookCategoryGroupBy](ctx, wcgb.build, wcgb, wcgb.build.inters, v)
}

func (wcgb *WorkbookCategoryGroupBy) sqlScan(ctx context.Context, root *WorkbookCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wcgb.fns))
	for _, fn := range wcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wcgb.flds)+len(wcgb.fns))
		for _, f := range *wcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WorkbookCategorySelect is the builder for selecting fields of WorkbookCategory entities.
type WorkbookCategorySelect struct {
	*WorkbookCategoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (wcs *WorkbookCategorySelect) Aggregate(fns ...AggregateFunc) *WorkbookCategorySelect {
	wcs.fns = append(wcs.fns, fns...)
	return wcs
}

// Scan applies the selector query and scans the result into the given value.
func (wcs *WorkbookCategorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wcs.ctx, ent.OpQuerySelect)
	if err := wcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkbookCategoryQuery, *WorkbookCategorySelect](ctx, wcs.WorkbookCategoryQuery, wcs, wcs.inters, v)
}

func (wcs *WorkbookCategorySelect) sqlScan(ctx context.Context, root *WorkbookCategoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(wcs.fns))
	for _, fn := range wcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*wcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
