// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"study-pal-backend/ent/predicate"
	"study-pal-backend/ent/workbookcategoryclassification"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WorkbookCategoryClassificationDelete is the builder for deleting a WorkbookCategoryClassification entity.
type WorkbookCategoryClassificationDelete struct {
	config
	hooks    []Hook
	mutation *WorkbookCategoryClassificationMutation
}

// Where appends a list predicates to the WorkbookCategoryClassificationDelete builder.
func (wccd *WorkbookCategoryClassificationDelete) Where(ps ...predicate.WorkbookCategoryClassification) *WorkbookCategoryClassificationDelete {
	wccd.mutation.Where(ps...)
	return wccd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (wccd *WorkbookCategoryClassificationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, wccd.sqlExec, wccd.mutation, wccd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (wccd *WorkbookCategoryClassificationDelete) ExecX(ctx context.Context) int {
	n, err := wccd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (wccd *WorkbookCategoryClassificationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(workbookcategoryclassification.Table, sqlgraph.NewFieldSpec(workbookcategoryclassification.FieldID, field.TypeUUID))
	if ps := wccd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, wccd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	wccd.mutation.done = true
	return affected, err
}

// WorkbookCategoryClassificationDeleteOne is the builder for deleting a single WorkbookCategoryClassification entity.
type WorkbookCategoryClassificationDeleteOne struct {
	wccd *WorkbookCategoryClassificationDelete
}

// Where appends a list predicates to the WorkbookCategoryClassificationDelete builder.
func (wccdo *WorkbookCategoryClassificationDeleteOne) Where(ps ...predicate.WorkbookCategoryClassification) *WorkbookCategoryClassificationDeleteOne {
	wccdo.wccd.mutation.Where(ps...)
	return wccdo
}

// Exec executes the deletion query.
func (wccdo *WorkbookCategoryClassificationDeleteOne) Exec(ctx context.Context) error {
	n, err := wccdo.wccd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{workbookcategoryclassification.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (wccdo *WorkbookCategoryClassificationDeleteOne) ExecX(ctx context.Context) {
	if err := wccdo.Exec(ctx); err != nil {
		panic(err)
	}
}
