// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"study-pal-backend/ent/predicate"
	"study-pal-backend/ent/problem"
	"study-pal-backend/ent/workbook"
	"study-pal-backend/ent/workbookcategory"
	"study-pal-backend/ent/workbookmember"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// WorkbookQuery is the builder for querying Workbook entities.
type WorkbookQuery struct {
	config
	ctx                    *QueryContext
	order                  []workbook.OrderOption
	inters                 []Interceptor
	predicates             []predicate.Workbook
	withProblems           *ProblemQuery
	withWorkbookCategories *WorkbookCategoryQuery
	withWorkbookMembers    *WorkbookMemberQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WorkbookQuery builder.
func (wq *WorkbookQuery) Where(ps ...predicate.Workbook) *WorkbookQuery {
	wq.predicates = append(wq.predicates, ps...)
	return wq
}

// Limit the number of records to be returned by this query.
func (wq *WorkbookQuery) Limit(limit int) *WorkbookQuery {
	wq.ctx.Limit = &limit
	return wq
}

// Offset to start from.
func (wq *WorkbookQuery) Offset(offset int) *WorkbookQuery {
	wq.ctx.Offset = &offset
	return wq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wq *WorkbookQuery) Unique(unique bool) *WorkbookQuery {
	wq.ctx.Unique = &unique
	return wq
}

// Order specifies how the records should be ordered.
func (wq *WorkbookQuery) Order(o ...workbook.OrderOption) *WorkbookQuery {
	wq.order = append(wq.order, o...)
	return wq
}

// QueryProblems chains the current query on the "problems" edge.
func (wq *WorkbookQuery) QueryProblems() *ProblemQuery {
	query := (&ProblemClient{config: wq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workbook.Table, workbook.FieldID, selector),
			sqlgraph.To(problem.Table, problem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, workbook.ProblemsTable, workbook.ProblemsColumn),
		)
		fromU = sqlgraph.SetNeighbors(wq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWorkbookCategories chains the current query on the "workbook_categories" edge.
func (wq *WorkbookQuery) QueryWorkbookCategories() *WorkbookCategoryQuery {
	query := (&WorkbookCategoryClient{config: wq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workbook.Table, workbook.FieldID, selector),
			sqlgraph.To(workbookcategory.Table, workbookcategory.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, workbook.WorkbookCategoriesTable, workbook.WorkbookCategoriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(wq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWorkbookMembers chains the current query on the "workbook_members" edge.
func (wq *WorkbookQuery) QueryWorkbookMembers() *WorkbookMemberQuery {
	query := (&WorkbookMemberClient{config: wq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(workbook.Table, workbook.FieldID, selector),
			sqlgraph.To(workbookmember.Table, workbookmember.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, workbook.WorkbookMembersTable, workbook.WorkbookMembersColumn),
		)
		fromU = sqlgraph.SetNeighbors(wq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Workbook entity from the query.
// Returns a *NotFoundError when no Workbook was found.
func (wq *WorkbookQuery) First(ctx context.Context) (*Workbook, error) {
	nodes, err := wq.Limit(1).All(setContextOp(ctx, wq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{workbook.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wq *WorkbookQuery) FirstX(ctx context.Context) *Workbook {
	node, err := wq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Workbook ID from the query.
// Returns a *NotFoundError when no Workbook ID was found.
func (wq *WorkbookQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = wq.Limit(1).IDs(setContextOp(ctx, wq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{workbook.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wq *WorkbookQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := wq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Workbook entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Workbook entity is found.
// Returns a *NotFoundError when no Workbook entities are found.
func (wq *WorkbookQuery) Only(ctx context.Context) (*Workbook, error) {
	nodes, err := wq.Limit(2).All(setContextOp(ctx, wq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{workbook.Label}
	default:
		return nil, &NotSingularError{workbook.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wq *WorkbookQuery) OnlyX(ctx context.Context) *Workbook {
	node, err := wq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Workbook ID in the query.
// Returns a *NotSingularError when more than one Workbook ID is found.
// Returns a *NotFoundError when no entities are found.
func (wq *WorkbookQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = wq.Limit(2).IDs(setContextOp(ctx, wq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{workbook.Label}
	default:
		err = &NotSingularError{workbook.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wq *WorkbookQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := wq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Workbooks.
func (wq *WorkbookQuery) All(ctx context.Context) ([]*Workbook, error) {
	ctx = setContextOp(ctx, wq.ctx, ent.OpQueryAll)
	if err := wq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Workbook, *WorkbookQuery]()
	return withInterceptors[[]*Workbook](ctx, wq, qr, wq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wq *WorkbookQuery) AllX(ctx context.Context) []*Workbook {
	nodes, err := wq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Workbook IDs.
func (wq *WorkbookQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if wq.ctx.Unique == nil && wq.path != nil {
		wq.Unique(true)
	}
	ctx = setContextOp(ctx, wq.ctx, ent.OpQueryIDs)
	if err = wq.Select(workbook.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wq *WorkbookQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := wq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wq *WorkbookQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wq.ctx, ent.OpQueryCount)
	if err := wq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wq, querierCount[*WorkbookQuery](), wq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wq *WorkbookQuery) CountX(ctx context.Context) int {
	count, err := wq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wq *WorkbookQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wq.ctx, ent.OpQueryExist)
	switch _, err := wq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wq *WorkbookQuery) ExistX(ctx context.Context) bool {
	exist, err := wq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WorkbookQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wq *WorkbookQuery) Clone() *WorkbookQuery {
	if wq == nil {
		return nil
	}
	return &WorkbookQuery{
		config:                 wq.config,
		ctx:                    wq.ctx.Clone(),
		order:                  append([]workbook.OrderOption{}, wq.order...),
		inters:                 append([]Interceptor{}, wq.inters...),
		predicates:             append([]predicate.Workbook{}, wq.predicates...),
		withProblems:           wq.withProblems.Clone(),
		withWorkbookCategories: wq.withWorkbookCategories.Clone(),
		withWorkbookMembers:    wq.withWorkbookMembers.Clone(),
		// clone intermediate query.
		sql:  wq.sql.Clone(),
		path: wq.path,
	}
}

// WithProblems tells the query-builder to eager-load the nodes that are connected to
// the "problems" edge. The optional arguments are used to configure the query builder of the edge.
func (wq *WorkbookQuery) WithProblems(opts ...func(*ProblemQuery)) *WorkbookQuery {
	query := (&ProblemClient{config: wq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wq.withProblems = query
	return wq
}

// WithWorkbookCategories tells the query-builder to eager-load the nodes that are connected to
// the "workbook_categories" edge. The optional arguments are used to configure the query builder of the edge.
func (wq *WorkbookQuery) WithWorkbookCategories(opts ...func(*WorkbookCategoryQuery)) *WorkbookQuery {
	query := (&WorkbookCategoryClient{config: wq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wq.withWorkbookCategories = query
	return wq
}

// WithWorkbookMembers tells the query-builder to eager-load the nodes that are connected to
// the "workbook_members" edge. The optional arguments are used to configure the query builder of the edge.
func (wq *WorkbookQuery) WithWorkbookMembers(opts ...func(*WorkbookMemberQuery)) *WorkbookQuery {
	query := (&WorkbookMemberClient{config: wq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wq.withWorkbookMembers = query
	return wq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Workbook.Query().
//		GroupBy(workbook.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wq *WorkbookQuery) GroupBy(field string, fields ...string) *WorkbookGroupBy {
	wq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WorkbookGroupBy{build: wq}
	grbuild.flds = &wq.ctx.Fields
	grbuild.label = workbook.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Workbook.Query().
//		Select(workbook.FieldCreatedAt).
//		Scan(ctx, &v)
func (wq *WorkbookQuery) Select(fields ...string) *WorkbookSelect {
	wq.ctx.Fields = append(wq.ctx.Fields, fields...)
	sbuild := &WorkbookSelect{WorkbookQuery: wq}
	sbuild.label = workbook.Label
	sbuild.flds, sbuild.scan = &wq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WorkbookSelect configured with the given aggregations.
func (wq *WorkbookQuery) Aggregate(fns ...AggregateFunc) *WorkbookSelect {
	return wq.Select().Aggregate(fns...)
}

func (wq *WorkbookQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wq); err != nil {
				return err
			}
		}
	}
	for _, f := range wq.ctx.Fields {
		if !workbook.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wq.path != nil {
		prev, err := wq.path(ctx)
		if err != nil {
			return err
		}
		wq.sql = prev
	}
	return nil
}

func (wq *WorkbookQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Workbook, error) {
	var (
		nodes       = []*Workbook{}
		_spec       = wq.querySpec()
		loadedTypes = [3]bool{
			wq.withProblems != nil,
			wq.withWorkbookCategories != nil,
			wq.withWorkbookMembers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Workbook).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Workbook{config: wq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := wq.withProblems; query != nil {
		if err := wq.loadProblems(ctx, query, nodes,
			func(n *Workbook) { n.Edges.Problems = []*Problem{} },
			func(n *Workbook, e *Problem) { n.Edges.Problems = append(n.Edges.Problems, e) }); err != nil {
			return nil, err
		}
	}
	if query := wq.withWorkbookCategories; query != nil {
		if err := wq.loadWorkbookCategories(ctx, query, nodes,
			func(n *Workbook) { n.Edges.WorkbookCategories = []*WorkbookCategory{} },
			func(n *Workbook, e *WorkbookCategory) {
				n.Edges.WorkbookCategories = append(n.Edges.WorkbookCategories, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := wq.withWorkbookMembers; query != nil {
		if err := wq.loadWorkbookMembers(ctx, query, nodes,
			func(n *Workbook) { n.Edges.WorkbookMembers = []*WorkbookMember{} },
			func(n *Workbook, e *WorkbookMember) { n.Edges.WorkbookMembers = append(n.Edges.WorkbookMembers, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (wq *WorkbookQuery) loadProblems(ctx context.Context, query *ProblemQuery, nodes []*Workbook, init func(*Workbook), assign func(*Workbook, *Problem)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Workbook)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(problem.FieldWorkbookID)
	}
	query.Where(predicate.Problem(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(workbook.ProblemsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.WorkbookID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "workbook_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (wq *WorkbookQuery) loadWorkbookCategories(ctx context.Context, query *WorkbookCategoryQuery, nodes []*Workbook, init func(*Workbook), assign func(*Workbook, *WorkbookCategory)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Workbook)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(workbookcategory.FieldWorkbookID)
	}
	query.Where(predicate.WorkbookCategory(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(workbook.WorkbookCategoriesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.WorkbookID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "workbook_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (wq *WorkbookQuery) loadWorkbookMembers(ctx context.Context, query *WorkbookMemberQuery, nodes []*Workbook, init func(*Workbook), assign func(*Workbook, *WorkbookMember)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Workbook)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(workbookmember.FieldWorkbookID)
	}
	query.Where(predicate.WorkbookMember(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(workbook.WorkbookMembersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.WorkbookID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "workbook_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (wq *WorkbookQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wq.querySpec()
	_spec.Node.Columns = wq.ctx.Fields
	if len(wq.ctx.Fields) > 0 {
		_spec.Unique = wq.ctx.Unique != nil && *wq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wq.driver, _spec)
}

func (wq *WorkbookQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(workbook.Table, workbook.Columns, sqlgraph.NewFieldSpec(workbook.FieldID, field.TypeUUID))
	_spec.From = wq.sql
	if unique := wq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wq.path != nil {
		_spec.Unique = true
	}
	if fields := wq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workbook.FieldID)
		for i := range fields {
			if fields[i] != workbook.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wq *WorkbookQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wq.driver.Dialect())
	t1 := builder.Table(workbook.Table)
	columns := wq.ctx.Fields
	if len(columns) == 0 {
		columns = workbook.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wq.sql != nil {
		selector = wq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wq.ctx.Unique != nil && *wq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wq.predicates {
		p(selector)
	}
	for _, p := range wq.order {
		p(selector)
	}
	if offset := wq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WorkbookGroupBy is the group-by builder for Workbook entities.
type WorkbookGroupBy struct {
	selector
	build *WorkbookQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wgb *WorkbookGroupBy) Aggregate(fns ...AggregateFunc) *WorkbookGroupBy {
	wgb.fns = append(wgb.fns, fns...)
	return wgb
}

// Scan applies the selector query and scans the result into the given value.
func (wgb *WorkbookGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wgb.build.ctx, ent.OpQueryGroupBy)
	if err := wgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkbookQuery, *WorkbookGroupBy](ctx, wgb.build, wgb, wgb.build.inters, v)
}

func (wgb *WorkbookGroupBy) sqlScan(ctx context.Context, root *WorkbookQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wgb.fns))
	for _, fn := range wgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wgb.flds)+len(wgb.fns))
		for _, f := range *wgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WorkbookSelect is the builder for selecting fields of Workbook entities.
type WorkbookSelect struct {
	*WorkbookQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ws *WorkbookSelect) Aggregate(fns ...AggregateFunc) *WorkbookSelect {
	ws.fns = append(ws.fns, fns...)
	return ws
}

// Scan applies the selector query and scans the result into the given value.
func (ws *WorkbookSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ws.ctx, ent.OpQuerySelect)
	if err := ws.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WorkbookQuery, *WorkbookSelect](ctx, ws.WorkbookQuery, ws, ws.inters, v)
}

func (ws *WorkbookSelect) sqlScan(ctx context.Context, root *WorkbookQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ws.fns))
	for _, fn := range ws.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ws.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ws.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
