// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Article is the predicate function for article builders.
type Article func(*sql.Selector)

// ArticleLike is the predicate function for articlelike builders.
type ArticleLike func(*sql.Selector)

// DescriptionProblem is the predicate function for descriptionproblem builders.
type DescriptionProblem func(*sql.Selector)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// SelectionProblem is the predicate function for selectionproblem builders.
type SelectionProblem func(*sql.Selector)

// SelectionProblemAnswer is the predicate function for selectionproblemanswer builders.
type SelectionProblemAnswer func(*sql.Selector)

// TrueOrFalseProblem is the predicate function for trueorfalseproblem builders.
type TrueOrFalseProblem func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Workbook is the predicate function for workbook builders.
type Workbook func(*sql.Selector)

// WorkbookCategory is the predicate function for workbookcategory builders.
type WorkbookCategory func(*sql.Selector)

// WorkbookCategoryClosure is the predicate function for workbookcategoryclosure builders.
type WorkbookCategoryClosure func(*sql.Selector)

// WorkbookInvitationMember is the predicate function for workbookinvitationmember builders.
type WorkbookInvitationMember func(*sql.Selector)

// WorkbookMember is the predicate function for workbookmember builders.
type WorkbookMember func(*sql.Selector)
